---
title: "Flujo de trabajo en videojuegos 3D"
---

{{< pagebreak >}}

Como ya hemos visto en otras asignaturas, el ciclo de vida del desarrollo de un videojuego se puede dividir en distintas etapas.
Aunque obviamente estas etapas pueden variar entre proyectos y estudios, en general el proceso siempre es muy similar:

```{mermaid}
%%| label: fig-gamedev-cycle
%%| fig-cap: "Ciclo de vida del desarrollo de un videojuego."
%%| file: figures/gamedev_cycle.mm
%%| fig-width: 6.2
```

En los siguientes apartados vamos a ver los pasos involucrados en la creación de los niveles de un juego, enmarcados en las etapas generales del desarrollo de un videojuego.

# Proceso de creación de niveles {#_proceso_de_creación_de_niveles}

En la @fig-level-production-pipeline podemos ver un esquema de los pasos involucrados en la creación de un nivel:

```{mermaid}
%%| label: fig-level-production-pipeline
%%| fig-cap: "Proceso de creación de niveles."
%%| file: figures/level_production_pipeline.mm
%%| fig-width: 6.2
```

Se han destacado en azul las tareas correspondientes a la etapa de preproducción y en naranja las de producción.
Sin embargo, no debemos olvidar que esto depende del proyecto y que algunas tareas realmente pueden aparecer en varias etapas.

Por ejemplo, el **diseño del juego** se define en las primeras etapas del desarrollo del videojuego, que son: **concepto** y **preproducción**.
Durante la etapa de **concepto** se establecen aspectos como el género, el argumento o el estilo artístico.
En esta etapa se elabora parte del **arte conceptual** ---aunque no lo hayamos indicado así en la @fig-level-production-pipeline--- de cara a mostrar adecuadamente el juego que se va a hacer, por ejemplo, con vistas a buscar la financiación necesaria.
Buena parte del **arte conceptual** se elabora durante la **preproducción** ---según se van definiendo aspectos concretos del juego--- al mismo tiempo que se diseña el juego con detalle y se elaboran documentos como el *Game Design Document* (GDD) o el *Art Design Document* (ADD).
El trabajo de los artistas conceptuales puede continuar durante la **producción**, bocetando niveles y elementos del juego antes de su modelado o cambios y elementos nuevos añadidos durante esa etapa.

Si, por ejemplo, miramos el arte conceptual de Sonic the Hedgehog[@SonicRetroConceptArt], podemos observar cómo en las primeras etapas, durante la conceptualización del juego, en algunos bocetos el personaje es completamente irreconocible, mientras que en otros es bastante similar al que conocemos.
En esas etapas los artistas desarrollan múltiples alternativas, hasta que se seleccionan aquellas que encajan con el estilo artístico, la historia, etc.
También podemos ver el trabajo posterior de los artistas conceptuales en producción, haciendo bocetos de los niveles y de las escenas cinemáticas.

El arte conceptual sirve como fuente de información y de inspiración para el modelado de personajes, objetos y edificaciones, y para la posterior composición de los niveles con ellos, durante la **producción**.
Otras fuentes de inspiración son las imágenes de referencia que los artistas buscan en Internet antes de ponerse a trabajar.

## Prototipado

Con el prototipado de niveles y mecánicas ocurre algo similar.
Buena parte del prototipado se realiza durante la **preproducción**, donde se hacen pruebas del *gameplay* y las reglas del juego para ver si «funcionan».
El resultado de la **preproducción** es el GDD ---entre otros documentos--- que debe incluir todos los detalles del diseño del juego, incluyendo las características ---o *stats*--- de personajes, armaduras y armas, temporizaciones de eventos y sistemas de combate, y la algoritmia involucrada.
Muchos de estos detalles se obtienen probando diferentes alternativas sobre los prototipos desarrollados.

También es posible que durante la etapa de **concepto** se desarrolle algún pequeño prototipo del juego, como forma de demostrar la viabilidad de la idea.
Y, durante la segunda mitad de la **preproducción**, a veces es necesario hacer un ***vertical slice***, que consiste en tomar una pequeña parte del juego y desarrollarla de forma acelerada hasta el final.
El objeto de este prototipo es ofrecer al editor e inversores una idea de cómo será el juego final, dado que seguramente tengan que aprobar el presupuesto y la planificación.
Además, permite identificar futuros problemas y ayuda en la estimación de las tareas y su tiempo, ya que permite obtener una idea de todo lo que debemos considerar durante el trabajo en la etapa de **producción**.

El prototipado de niveles en se puede hacer de múltiples maneras, según el tipo de juego y lo que se pretenda probar.
Puede ser usando herramientas analógicas, como lápiz y papel o legos, o con herramientas digitales, como Photoshop, Sketchup, Maya o el propio motor de videojuegos; o una combinación de varias de estas herramientas en distintas iteraciones sobre el prototipo.
Sea como fuere, en algún momento el nivel se prototipa usando un conjunto mínimo de recursos, empleando cajas y modelos de *stock* o de proyectos previos, y pocas o ninguna textura.
Por eso a esta fase se la denomina con nombres como: ***blocking***, ***greyboxing***, ***whiteboxing*** o ***blockout***.

En algunos estudios el ***greyboxing*** se hace pronto, desde fases muy tempranas de la **preproducción**, para probar y establecer las mecánicas y las características del diseño de niveles.
Cuando estas están lo suficientemente bien definidas, el proyecto pasa a la etapa de **producción**.
Para que eso ocurra no es necesario haber prototipado todo el juego, sino algunos niveles y las mecánicas principales, en los que se ha iterado hasta refinar el diseño lo suficiente como para tener unas guías claras para la siguiente etapa.

Durante la producción, el ***greyboxing*** sigue siendo extremadamente útil para el diseño y prototipado del resto de niveles del juego, solo que los diseñadores pueden explorar y probar el nivel con un *gameplay* más próximo a como serán en el producto final.

# Después del prototipado

Una vez el ***greyboxing*** de un nivel se da por terminado y el *gameplay* funciona, se compone el nivel con las mallas estáticas definitivas.
Posteriormente, se ilumina el nivel, para lo cual los artistas usan para guiarse imágenes de referencia de cómo se quiere que sea la iluminación.

Para la iluminación del nivel:

1. El primer paso es darle al nivel el ambiente adecuado.
Se suele empezar por fuentes de luz primarias, como el sol o la luna ---con una fuente direccional--- y la iluminación ambiental ---como el *Sky Light* en Unreal Engine---.
En interiores se pueden usar focos, luces puntuales y rectangulares.

1. Después se añaden fuentes para destacar detalles o simular ciertos efectos, como: focos, pantallas, fuegos, antorchas, velas, etc.

1. A continuación se incorpora la iluminación funcional, es decir, aquella que va dirigida a modular el *gameplay*.
Se pueden iluminar puzles, áreas a explorar, puntos de entrada de los enemigos o dar pistas sobre posibles estrategias.
También se pueden iluminar salidas e incluso dar alguna indicación sobre la ruta, especialmente en niveles complejos.
En este sentido es interesante tener una jerarquía.
Las salidas más importantes deberían destacar más.

1. Finalmente se hace el ajuste fino de toda la iluminación.

En esta fase también se suelen incorporar los efectos de posprocesos, dado que afectan y se ven afectados por la iluminación.

Por último, se itera puliendo los detalles del nivel; añadiendo: sonidos, sistemas de partículas y reflexiones; y se optimiza su funcionamiento en las distintas plataformas.

# Greyboxing

La idea del ***greyboxing*** es obtener un bosquejo aproximado ---sin detalles ni texturas, usando figuras geométricas básicas--- de la distribución del nivel para centrar la atención sobre características principales como: tamaño, escala, proporciones, composición y espacio jugable.
Hacer el ***greyboxing*** en el propio motor de videojuegos abre la puerta a ir desarrollando y probando el código de *gameplay* al mismo tiempo e iterar probando el diseño, refinando así aspectos como: navegabilidad, durabilidad, ritmo[^1] del nivel y fluir[^2] del juego.

[^1]: El ritmo o *pacing* de un nivel es el orden general y la cadencia de las actividades y eventos del nivel.

[^2]: Un nivel con buen control del *flow* dirige al jugador hacia el objetivo, evitando parones y momentos de confusión no intencionados en el juego.

![Blocking en Maya a partir de un diseño en papel[@Galuzin2009BlokingMaya].](figures/blocking_in_maya.jpg)

Durante la **producción**, cuando los modelos estáticos y animados estén listos, las cajas del ***greyboxing*** son reemplazadas para componer el nivel definitivo.

En una primera etapa, es aconsejable crear planos en papel de las diferentes plantas del nivel, considerando las restricciones establecidas por los equipos de diseño y desarrollo.
Posteriormente, estos planos se trasladan al ***greyboxing*** del nivel, usando figuras geométricas básicas, sin detalles, con texturas de desarrollo y solo empleando una iluminación muy básica.
Algunos diseñadores con experiencia prefieren comenzar a trabajar en un nivel empezando directamente por el ***greyboxing*** en 3D.

Es importante recordar que el ***greyboxing*** es un prototipo del diseño, por lo que cambiarán según se prueba y avanza el desarrollo del juego.
Así que debe ser modular, sencillo de modificar y sin detalles; porque durante las iteraciones del diseño muchos aspectos serán desechados o cambiados.

::: {.callout-note}
Cada primero de octubre arranca el *Blocktober*, un evento en el que durante un mes diseñadores y artistas comparten *blockouts* para mostrar la fase inicial de sus creaciones.
Algunos incluso comparten algunas de las iteraciones, para mostrar la evolución desde el *blockouts* hasta el resultado final.
Para ver los trabajos, basta con buscar el *hashtag* {{< var twitter.blocktober >}} en Twitter.
:::

En muchos casos se hace ***greyboxing*** de niveles muy básicos, solo para servir de *sandbox* donde probar mecánicas, sistemas y reglas de diseño.
Estos niveles no se siguen desarrollando, una vez han servido para su cometido, ni se incorporan al juego terminado.

## Rejillas y escalas

Antes de comenzar con el *greyboxing* es importante estandarizar el tamaño de la rejilla espacial que se va a usar para ubicar los elementos y adherirnos a ella fielmente durante el diseño de niveles.
Fijar que, por ejemplo, la unidad de altura estándar de los muros será de 3 m y que los segmentos de suelo serán de 3x3 m.
Esto no significa que no pueda haber objetos en posiciones intermedias de la rejilla para dotar de mayor detalle a la escena, pero para eso se recomienda usar siempre divisiones pares de la cuadrícula estándar escogida.

Para escoger un buen sistema de rejilla hay que tomar en consideración las escalas o tamaños de los objetos, personajes y edificaciones.
Para escalar adecuadamente los elementos del nivel, se puede añadir desde el principio un modelo de «dimensiones humanas» como referencia ---o cualquier otro objeto que tenga sentido según el caso--- y estandarizar las medidas de distintos tipos de objetos para usarlas en todos los niveles.

::: {.tip}
En proyectos de realidad virtual se pueden utilizar como referencia los modelos de los controladores que hacen de manos.
:::

Otro aspecto a considerar al establecer escalas es el campo de visión y las distorsiones derivadas del punto de vista del jugador.
En juegos en primera persona, huecos como los de puertas y ventana parecen un poco más pequeños de lo que son en realidad, dando la impresión de que no cabemos por ellos.
Mientras que situar la cámara demasiado alta ---más de 2 m--- o demasiado bajo ---menos de 1.5 m--- tiende a distorsionar la perspectiva, dado que el cerebro del jugador asume que la altura de la cámara debe ser similar a la altura real de los ojos.
En juegos en tercera persona, en interiores con escala real, el jugador tiene la impresión de que el espacio es demasiado pequeño.
Por eso se tiende a crear habitaciones más amplias, con mobiliario de tamaño real ---o solo un poco más grande--- repartido por la habitación para llenarla[@Schell2019ArtGameDesign].

También es importante tener en cuenta las mecánicas de juego y las animaciones.
Por ejemplo ¿a qué velocidad se moverá el personaje?, ¿cuánto saltará el personaje?, ¿a qué distancia?, ¿qué altura tiene cuando está de pie?, ¿y cuándo está agachado?, ¿cuánto espacio necesita para moverse?, ¿a qué altura estarán los paneles e interruptores con los que va a interactuar? Si por ejemplo las paredes van a hacerse en unidades de 3 m, el personaje puede medir 1.5 m, los huecos para cruzar agachado 0.5 m y los interruptores y paneles pueden estar a 1 m Si los elementos del suelo se pueden ajustar en una rejilla de 1x1 m eso determinar cuánto debe poder saltar el personaje, el ancho de los obstáculos que debe poder superar y el largo de cada tramo de escalera, entre otras cosas.

Un sistema de rejilla bien diseñado simplifica el trabajo de diseño, reduce el tiempo de ensayo y error y evita que se acabe rehaciendo mucho trabajo al prevenir incoherencias.
Sin embargo, la escalas de los objetos y la rejilla no son lo único que hace falta estandarizar antes de comenzar.
También es conveniente fijar las reglas para colocar los orígenes en los modelos ---por ejemplo, siempre abajo y a la izquierda--- y el nivel de modularidad.

Lo primero, facilita la sustitución de los bloques por las mallas definitivas y la composición del nivel, si respetamos estas reglas tanto en el *greyboxing* como en las mallas modeladas.
Mientras que la modularidad permite obtener niveles con alto nivel de detalle, pero necesitando menos trabajo de modelado y texturizado al facilitar la reutilización de elementos por todo el juego.
Es decir, en un juego de carreras urbanas es bastante razonable que cada edificación se modele mediante una malla, que se pueden reutilizar en diferentes puntos de la ciudad, variando levemente el color y otros detalles.
Se puede obtener más variedad con menos trabajo modelando módulos de 2 o 3 plantas de edificio y apilando estos módulos unos sobre otros, de diferentes maneras, para construir las edificaciones.

En un *survival horror* que transcurre en los estrechos pasillos de una nave espacial, se pueden modelar las paredes, techo y suelo de cada estancia en una sola malla, que se puede reutilizar en varios puntos del juego.
Utilizar un único modelo hace que cada estancia utilice un único *ligthmap*, lo que evita algunos problemas con la iluminación precalculada; pero tampoco es raro optar por una solución aún más modular, donde los paneles se construyen uniendo mallas individuales de tamaño fijo.
La combinación de estas mallas individuales permite obtener estancias diferentes con múltiples variaciones de paredes, techos y pisos.

En todo caso, en el *greyboxing* no tenemos por qué usar el mismo nivel de modularidad que en la geometría definitiva del nivel.
Lo importante que es que sea flexible, para que podamos iterar rápidamente en el diseño del nivel.
Por ejemplo, si creamos las estancias usando bloques de tamaño fijo ---a imitación de como serán los módulos de las mallas definitivas--- después podremos sustituir cada bloque directamente por un modelo, para componer el nivel definitivo.
Sin embargo, al hacerlo así puede resultar más complejo modificar la geometría de las estancias al iterar durante el *greyboxing*.

## Manos a la obra

Es recomendable comenzar a trabajar a un nivel macro, haciendo uso de cajas de gran tamaño, con las que repartir los espacios, para posteriormente ir añadiendo algo más de detalle, empezando por los elementos más destacables del nivel.
Si está bastante claro cómo debe jugarse el nivel, entonces tendremos una idea clara de cómo organizar el espacio jugable[^3], lo que nos puede servir como punto de partida para construir el nivel.
Si por el contrario estamos en una etapa muy temprana del desarrollo y aún no tenemos claro cómo es el espacio del juego, podemos comenzar explorando alguno de los patrones más comunes: lineal, rejilla, telaraña, puntos en el espacio o espacio dividido (véase @Schell2019ArtGameDesign para conocer más detalles sobre estos patrones y algunos ejemplos).

[^3]: En [@Schell2019ArtGameDesign] se define el *espacio funcional* como aquel donde tienen lugar el juego, una vez se han eliminado todos los elementos superficiales.

![Greybox para «Shooty Squad»[@Dillon2018Greybox].](figures/blocking.jpg){#fig-greybox-shooty-squad}

Según avanza el prototipo, se van añadiendo personajes, animaciones y otros elementos.
Se programan eventos y se prueba el diseño de niveles, las distancias y tiempos entre puntos importantes, el ritmo del juego y el *gameplay*.
Basándonos en los resultados de estas pruebas, se modifican las mecánicas y los niveles y se vuelve a iterar.
Si aún estamos en **preproducción**, reuniendo requisitos del *gameplay* y características del diseño de niveles, estos se recogerán para incluirlos en el GDD.

Si bien el prototipado de niveles es una tarea en la que participan principalmente programadores y diseñadores, es importante que haya comunicación con el equipo de arte para coordinar el *look-and-feel*.
Los artistas trabajan con los diseñadores de nivel mientras crean el arte conceptual, que posteriormente servirá para el modelado de los elementos que compondrán los niveles.
Los bloques del *greyboxing* pueden representar cualquier cosa, así que es importante documentar las intenciones para facilitar la comunicación.
Incluso puede ser buena idea hacer algunas capturas del nivel desde distintos ángulos y pintar encima, con el objeto de comunicar expectativas, incluso dentro del equipo de diseñadores.

::: {.callout-note}
En ocasiones, los niveles diseñados mediante *greyboxing* se exportan para que los modeladores los usen en sus programas como referencia.
En algunos casos los modeladores trabajan sobre el nivel completo, mientras en otros lo hacen sobre una colección de pequeños componentes individuales con los que luego compondrán el nivel definitivo.
:::

## Herramientas para *greyboxing*

Se puede hacer *greyboxing* en programas 3D como Maya, 3ds Max o Sketchup.

![Greybox en Sketchup de niveles de «A Plague Tale: Innocence» (2019)[@Arrow2021Greybox].](figures/blocking_sketchup.png)

Sin embargo, eso implica tener que exportar e importar los diseños de un programa a otro para probarlos.
Así que, si el motor de videojuegos tiene un editor adecuado, es mejor hacer el *greyboxing* en él para ahorrar tiempo e iterar más rápido durante el diseño.

### Unreal Engine

En Unreal Engine se pueden utilizar **Geometry Brushes**[@UnrealGeometricBrush] para prototipar.
Las **Geometry Brushes** se empleaban en el pasado para construir la geometría definitiva del nivel, pero en la actualidad es preferible que los modeladores la creen con herramientas externas, para luego importarla como **Static Meshes** en el editor de UE.
Por eso, actualmente, las **Geometry Brushes** prácticamente solo se usan para prototipar mecánicas y niveles.

Las **Geometry Brushes** permiten crear formas básicas, como: cajas, esferas, conos, cilindros o escaleras.
También permiten operar con ellas, modificando sus propiedades o sumando y restando formas, para crear otras más complejas.

El vídeo «HTF do I? Whiteboxing with BSP in Unreal Engine 4»[@Wadstein2015Whiteboxing] es un sencillo tutorial sobre el uso de **Geometry Brushes**.
Es interesante observar cómo crea materiales para *greyboxing* con diferentes colores.
Estos son útiles para señalar distintas zonas de juego, tipos de elementos o señalar nuestros cambios respecto a un diseño anterior.

Unreal Engine tiene además un conjunto de herramientas de edición denominadas **Geometry Editing**, con el que se pueden modificar directamente las figuras en el editor.
El mismo autor del vídeo anterior tiene una interesante colección de tutoriales[@Wadstein2016GeometryEditing] sobre los modos de **Geometry Editing**: **Edit**, **Pen**, **Lathe**, **Brush Clip** y **Extrude**.
El [???](#video-ue-geometry-editing) es el primero, sobre el modo **Edit**.

En [@Sergeev2020BlockoutsStarWars] se pueden ver algunos ejemplos del *greyboxing* en Unreal Engine y el resultado final en «Star Wars Jedi: Fallen Order» (2019).

Además de las herramientas del editor de Unreal Engine, en el {{< var unreal.marketplace >}} hay algunos complementos interesantes para prototipar.
Dos que merece la pena destacar son Mesh Tool[@NateMeshTool] y Blockout Tools Plugin[@KarpukhinBlockoutTools].

### Unity

Unity trae de serie algunos objetos primitivos que se pueden usar para prototipar: cubo, plano, esfera, cápsula, cilindro y cuadrado.
Sin embargo, es recomendable aprender a usar ProBuilder[@UnityProbuilder], que se distribuye como un paquete independiente.

ProBuilder está optimizado para crear formas sencillas, pero también ofrece herramientas de edición avanzadas, asignación de materiales y edición de UV, de forma similar a otros programas de modelado 3D.
Las mayas creadas con ProBuilder son iguales a las que se importan en Unity desde programas externos.
La @fig-greybox-shooty-squad es una muestra de lo que permite hacer.

ProBuilder trae algunas formas básicas que se pueden modificar mediante distintos modos de edición: **Vertex**, **Edge** y **Face**; para generar formas más complejas En estos modos se pueden seleccionar vértices, aristas o caras, respectivamente, para transformarlos y cambiar totalmente la forma de la geometría.
Una vez tenemos el objeto deseado, se pueden asignar colores a los vértices para marcar zonas del diseño o aplicar materiales.

En la página principal de Probuilder[@UnityProbuilder] hay enlazados varios tutoriales donde se explica cómo utilizarlo.
Uno de ellos es «ProBuilder Greyboxing an Interior FPS Level»[@Unity2018Greyboxing], que muestra cómo hacer el *greyboxing* de un nivel para un FPS.

Otra tarea para la que se puede utilizar ProBuilder es para añadir la geometría de colisión del nivel para, por ejemplo, limitar las áreas por las que pueden desplazarse los personajes.
En el vídeo «Simplify Collision Geometry in Unity, with ProBuilder»[@Williams2016Collisions] se muestra cómo se hace esto mediante un ejemplo muy sencillo.

ProBuilder es más cómodo y rápido de usar si se emplea junto a ProGrids[@UnityProgrids], una herramienta que ofrece mejoras funcionales y visuales respecto a la rejilla y el *snapping* que trae el editor de Unity.

::: {.callout-tip}
Las ventajas de usar ProGrids se notan menos a partir de Unity 2019.4, ya que el editor ha incorporado algunas de sus características.
:::

Además de ProBuilder, en la Asset Store podemos encontrar herramientas algo más sencillas y orientadas al *greyboxing*.
Las más conocidas son SabreCSG[@SabresaurusLevelDesign] y RealtimeCSG[@PrenominalRealtimeCSG].
Como su nombre indica, ambas utilizan la técnica *Constructive Solid Geometry* (CSG).
Esta técnica permiten realizar operaciones de adición y sustracción sobre figuras básicas para crear figuras más complejas, igual que como funcionan las **Geometry Brushes** de Unreal Engine.

# Referencias

::: {#refs}
:::