project:
  output-dir: _output
  render:
    - content/01_flujo_de_trabajo/flujo_de_trabajo.qmd
    - content/02_introducción_gameplay/colisiones_y_triggers.qmd
    - content/02_introducción_gameplay/entrada_e_interacción.qmd
    - content/02_introducción_gameplay/control_de_personajes_y_armas.qmd
    - content/extras/perforce/perforce.qmd
    - content/extras/estructura_proyectos/estructura_proyectos.qmd
    - content/unreal/unreal_gameplay_framework/unreal_gameplay_framework.qmd

subtitle: Desarrollo de Videojuegos 3D (20XX/20XY)
author:   
  - name: Jesús Torres
    email: jmtorres@ull.es
    url: https://jesustorres.es/
    affiliation: Universidad de La Laguna
    affiliation-url: https://www.ull.es/ 
thanks: |
  Este trabajo © 2020-2024 está bajo una licencia [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.es).
copyright:
  holder: Jesús Torres
  year: 2023
  license: CC BY 4.0
  license-url: https://creativecommons.org/licenses/by/4.0/deed.es

abstract: |
  ::: {.callout-caution appearance="simple"}
  El **tiempo estimado de lectura** es de {{< meta reading-time.formatted >}}.
  :::

lang: es
abstract-title: Resumen
toc-title: Contenidos
toc: true
number-sections: true
crossref:
  title-delim: period

suppress-bibliography: false
bibliography: references/references.bib
csl: references/chicago-fullnote-bibliography-short-title-subsequent.csl

filters:
  - reading-time
  - quarto
  - api-reference

format:
  pdf:
    # keep-tex: true
    documentclass: scrartcl
    classoption: numbers=endperiod
    papersize: a4
    include-before-body: 
      text: |
        %% Enable hyphenation for tt fonts
        \DeclareFontFamily{\encodingdefault}{\ttdefault}{\hyphenchar\font=`\-}
        \hyphenation{In-terp-To-Mo-ve-ment-Com-po-nent}
        \hyphenation{Add-Con-tro-ller-Yaw-In-put}
        \hyphenation{Pla-yer-Ca-me-ra-Ma-na-ger}
        \hyphenation{Set-Com-po-nent-Tick-E-na-bled}
        \hyphenation{Cha-os-Whee-led-Ve-hi-cle-Mo-ve-ment-Com-po-nent}
        \hyphenation{Cha-os-Ve-hi-cle-Mo-ve-ment-Com-po-nent}
        \hyphenation{Up-da-te-Vi-ew-Tar-get-In-ter-nal}
        \hyphenation{Blu-e-print-Up-da-te-Ca-me-ra}
        \hyphenation{In-ter-nal-Ta-ke-Ra-di-al-Da-ma-ge}
        \hyphenation{Cha-rac-ter-Mo-ve-ment-Com-po-nent}

api-reference: 
  path: references/api.yml