project:
  output-dir: _output
  render:
    - content/01_flujo_de_trabajo/flujo_de_trabajo.qmd
    - content/02_introducción_gameplay/colisiones_y_triggers.qmd
    - content/02_introducción_gameplay/entrada_e_interacción.qmd
    - content/02_introducción_gameplay/control_de_personajes_y_armas.qmd
    - content/extras/perforce/perforce.qmd
    - content/extras/estructura_proyectos/estructura_proyectos.qmd
    - content/unreal/unreal_gameplay_framework/unreal_gameplay_framework.qmd

subtitle: Desarrollo de Videojuegos 3D (20XX/20XY)
institute: Master Universitario en Desarrollo de Videojuegos de la Universidad de La Laguna
author:   
  - name: Jesús Torres
    email: jmtorres@ull.es
author-meta: Jesús Torres <jmtorres@ull.es>
copyright:
  license: Este trabajo está bajo una licencia [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.es).

abstract: |
  ::: {.callout-caution appearance="simple"}
  El **tiempo estimado de lectura** es de {{< meta reading-time.formatted >}}.
  :::

lang: es
abstract-title: Resumen
toc-title: Contenidos
toc: true
number-sections: true
crossref:
  title-delim: period

suppress-bibliography: false
bibliography: references/references.bib
csl: references/chicago-fullnote-bibliography-short-title-subsequent.csl
api-reference: 
  path: references/api.yml

hyphenation:
  - In-terp-To-Mo-ve-ment-Com-po-nent
  - Add-Con-tro-ller-Yaw-In-put
  - Pla-yer-Ca-me-ra-Ma-na-ger
  - Set-Com-po-nent-Tick-E-na-bled
  - Cha-os-Whee-led-Ve-hi-cle-Mo-ve-ment-Com-po-nent
  - Cha-os-Ve-hi-cle-Mo-ve-ment-Com-po-nent
  - Up-da-te-Vi-ew-Tar-get-In-ter-nal
  - Blu-e-print-Up-da-te-Ca-me-ra
  - In-ter-nal-Ta-ke-Ra-di-al-Da-ma-ge
  - Cha-rac-ter-Move-ment-Com-po-nent
  - Pawn-Move-ment-Com-po-nent
  - Get-Con-trol-Ro-ta-tion
  - Add-Pitch-In-put
  - Over-lap-Block-ing-Test-By-Chan-nel
  - Over-lap-Block-ing-Test-By-Pro-file
  - Line-Trace-Sin-gle-By-Ob-ject-Type
  - Line-Trace-Multi-By-Ob-ject-Type
  - Line-Trace-Test-By-Ob-ject-Type
  - Add-Ac-tor-World-Off-set
  - Set-Ac-tor-Trans-form
  - Set-World-Trans-form
  - Set-Ac-tor-Rel-a-tive-Trans-form
  - Set-Rel-a-tive-Lo-ca-tion-And-Ro-ta-tion

filters:
  - reading-time
  - quarto
  - api-reference

format:
  pdf:
    # keep-tex: true
    documentclass: scrartcl
    classoption: numbers=endperiod
    papersize: a4
    template-partials:
      - partials/title.tex
      - partials/before-body.tex