project:
  type: book

book:
  title: Desarrollo de Videojuegos 3D
  subtitle: Master Universitario en Desarrollo de Videojuegos de la Universidad de La Laguna (Cursos 20XX/20XY)
  date: today
  author:
    - name: Jesús Torres
      email: jmtorres@ull.es
  publisher: Universidad de La Laguna
  page-footer: |
    Este trabajo está bajo una licencia [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.es)
    <img style="height:16px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt="">
    <img style="height:16px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a> 
  # abstract: 
  chapters: 
    - index.qmd
    - part: Workflow
      chapters: 
        - content/workflow/motores.qmd
    - part: Animación
      chapters:
        - content/animación/motion_matching.qmd
  # appendices:

lang: es
toc-title: Contenidos
callout-appearance: simple
crossref:
  title-delim: ":"
  custom:
    - kind: float
      reference-prefix: Video
      key: vid

bibliography: references/references.bib
csl: references/elsevier-with-titles.csl
reference-section-title: Referencias

api-reference:
  path: references/api.yml
  reference-section-title: Referencias a la API
  markers:
    class: "{{< iconify tabler square-letter-c-filled >}}"
    event: "{{< iconify tabler circle-letter-e-filled >}}"
    function: "{{< iconify tabler circle-letter-f-filled >}}"
    method: "{{< iconify tabler circle-letter-m-filled >}}"

filters:
  - reading-time
  - quarto
  - api-reference
  - section-bibliographies

format:
  html:
    css: styles.css
    number-sections: true
    number-depth: 3
    anchor-sections: true
    smooth-scroll: true
    html-math-method: katex
    mermaid:
      theme: default
    include-in-header: 
      text: '<meta name="robots" content="noindex, nofollow">'
    resources:
      - robots.txt