graph TD
    subgraph GameEngine["<strong>Motor de videojuegos</strong>"]
        LevelComposition(["<strong>Composición<br>del nivel</strong>"]) --> FinalLevelComposition("<strong>Composición<br>final del nivel</strong>")
        Terrain("<strong>Terreno</strong>") --> FinalLevelComposition
        Sound("<strong>Sonido</strong>") --> FinalLevelComposition
        Lighting("<strong>Iluminación</strong>") --> FinalLevelComposition
        VFX("<strong>VFX</strong><br><small>Sistemas de partículas, decals,<br>efectos de iluminación y shaders</small>") --> FinalLevelComposition
        Scripting("<strong>Scripting</strong><br><small>Instanciación de NPC, activación<br>de cinemáticas, puertas y otros<br>eventos del gameplay</small>") --> FinalLevelComposition
        
        FinalLevelComposition --> LevelOptimization(["<strong>Optimización del nivel</strong><br><small>Asegurar que el nivel funciona adecuadamente<br>en las diferentes plataformas</small>"])

        style LevelComposition fill:#FFD580,stroke:orange
        style LevelOptimization fill:#FFD580,stroke:orange
    end
