# Introducción {.unnumbered}

Los motores de videojuegos ofrecen componentes y servicios comunes que pueden necesitar cualquier aplicación multimedia interactiva: render, iluminación, lectura de la entrada y creación de interfaces de usuario, simulación física, efectos visuales, sistemas de animación, gestión de recursos, carga y almacenamiento de datos, etc.
Sin embargo, desde el punto de vista del desarrollo, esto no es suficiente para hacer un videojuego.

Sobre los componentes y sistemas proporcionados por el motor se suele implementar una arquitectura software adecuada para el tipo de juego que se quiere desarrollar, a veces denominada *gameplay framework*.
El objetivo de estos componentes es facilitar la implementación de las mecánicas del juego, de forma que el código sea fácil de mantener y extender. 
Además, se suelen desarrollar a lo largo de diferentes proyectos de un mismo estudio, de forma que se van mejorando y adaptando a las necesidades de cada uno, y ayuda a reducir el tiempo de desarrollo.

Por lo general, los motores de videojuegos generalistas no ofrecen un *gameplay framework* predefinido, sino que cada estudio desarrolla el suyo propio, adaptado a sus necesidades y al tipo de juegos que desarrolla.
Sin embargo, el motor Unreal Engine sí ofrece un *gameplay framework*[@UnrealGameplayFramework], aunque muy orientado al tipo de juegos que hace Epic Games --es decir, videojuegos de acción competitivos en primera o tercera persona--.

A continuación veremos qué nos ofrece este *gameplay framework*, puesto que se trata de un buen ejemplo de cómo organizar el código de un videojuego y nos puede ofrecer ideas que podemos trasladar a otros motores --como Unity o Godot-- o a otro tipo de juegos.