# Level Blueprint

Aunque no está relacionado con el *gameplay framework*, merece la pena señalar que cada nivel en Unreal Engine tiene asociado un **Level Blueprint** donde se puede escribir código global del nivel.

En otros motores esto se asemeja a tener un *level manager*.
Sin embargo, en Unreal Engine el papel de *level manager* se divide, más bien, entre el **GameMode** y el **Level Blueprint**.

Como el **Level Blueprint** tiene acceso directo a todos actores del nivel, es muy útil para implementar la lógica que conecta los eventos globales del nivel, para que los actores se coordinen.
Por ejemplo, establecer suscripciones a eventos para que cuando el actor del jugador llegue a cierto punto del nivel se active un evento que haga que se instancien enemigos, se activen unas plataformas, etc.
Mientras que el **GameMode** suele contener el resto del código de gestión del nivel.

El **Level Blueprint** se puede editar desde el editor de Unreal Engine, seleccionando la opción **Blueprints / Open Level Blueprint** en el menú principal.

<!-- TODO: Captura de un LevelBlueprint -->

El **Level Blueprint** es un actor de tipo `ALevelScriptActor` que es creado automáticamente por la instancia de **UWorld**.

Se puede heredar de la clase `ALevelScriptActor` en C++ para crear una nueva clase base de **Level Blueprint**[Más en @TorresD3DUnrealCpp].
Esto se suele hacer para incorporar métodos útiles o exponer ciertas funcionalidades al código de Blueprint en el **Level Blueprint**.