# Gameplay

El *gameplay* en un videojuego se refiere a la forma en la que el jugador interactúa con el juego, incluyendo los controles, las mecánicas de juego, objetivos y desafíos.
Es la experiencia del jugador mientras está jugando y cómo se siente al hacerlo.

El *gameplay* se puede dividir en varias categorías, como la exploración, la resolución de puzzles, el combate, la estrategia o la simulación.
Cada uno de estos tipos de *gameplay* ofrece diferentes desafíos y experiencias al jugador, y muchos juegos combinan varios tipos de *gameplay* para crear una experiencia única y diversa.

Nosotros vamos a centrarnos en aquellos aspectos del *gameplay* relacionados o condicionados por el desarrollo de un juego en un mundo 3D.
Pero, obviamente, debemos tener presente que en un juego en 3D puede haber mucha lógica de *gameplay* que nada tenga que ver con las características del entorno de juego ni con el motor de videojuegos.
Por ejemplo, el sistema que gestiona el inventario del jugador, el sistema de habilidades --típico en muchos juegos con algún componente de RPG-- o el combate en los juegos de estrategia se pueden desarrollar y probar independientemente del juego y del motor de videojuegos.

Lo mismo ocurre con los simuladores de granjas, fábricas o de ciudades, pues en realidad lo que se muestra al jugador no es sino una interfaz elegante y vistosa de la simulación, que puede --y debe-- desarrollarse de forma completamente independiente de esta.

::: {.callout-note}
Para quienes están familiarizados con el patrón de arquitectura de software Modelo-Vista-Controlador y sus variantes, podemos decir que en estos juegos de simulación, así como en los típicos juegos de puzzles para móviles; la simulación o la lógica de los puzzles se prestan a ser considerarlos el modelo, mientras la interfaz del juego sería la vista.
Seguir este enfoque puede ayudar mucho en el desarrollo del juego.
:::

Incluso en simuladores de carreras o de vuelo, la simulación de la dinámica de los vehículos --cuando se busca una experiencia más realista que tipo *arcade*-- puede desarrollarse independientemente de otros aspectos del juego.
Obviamente, luego es necesario encajar dicha simulación en el mundo 3D del juego, teniendo en cuenta sus limitaciones.

En general, para un juego 3D nos interesa saber cómo mover y hacer interactuar personaje con el entorno y cómo usar la entrada del jugador para controlar el personaje.
