classDiagram
    UObject <|-- Actor
    
    Actor <|-- Pawn
    Actor <|-- TriggerBase
    TriggerBase <|-- TriggerBox
    TriggerBase <|-- TriggerSphere
    TriggerBase <|-- TriggerCapsule

    Actor <|-- Brush
    Brush <|-- Volume
    Volume <|-- TriggerVolume
    
    UObject <|-- ActorComponent
    UObject <|-- UWorld

    ActorComponent <|-- SceneComponent
    note for SceneComponent "Puede ser ubicados<br>en la escena."
    ActorComponent <|-- MovementComponent

    SceneComponent <|-- PrimitiveComponent
    note for PrimitiveComponent "Generan algún tipo<br>de geometría como para<br>render o colisión."    
    PrimitiveComponent <|-- ShapeComponent
    PrimitiveComponent <|-- StaticMeshComponent
    PrimitiveComponent <|-- BrushComponent
    ShapeComponent <|-- BoxComponent
    ShapeComponent <|-- SphereComponent
    ShapeComponent <|-- CapsuleComponent