graph TB
  Assets([Assets]) --> Character([Character])
  Assets --> Enemies([Enemies])
  Assets --> Environment([Environment])
  Assets --> Effects([Effects])
  Assets --> Prefabs([Prefabs])
  Assets --> Scenes([Scenes])
  Assets --> Scripts([Scripts])
  Assets --> Sounds([Sounds])
  Assets --> UI([UI])
  Assets --> Weapons([Weapons])

  %% Character --> CharacterMaterials([Materials])
  %% Character --> CharacterMeshes([Meshes])
  %% Character --> CharacterTextures([Textures])

  %% Enemies --> Tanks([Tanks])
  %% Enemies --> Robots([Robots])

  %% Tanks --> TanksMaterials([Materials])
  %% Tanks --> TanksMeshes([...])

  %% Robots --> RobotsMaterials([Materials])
  %% Robots --> RobotsMeshes([...])

  Environment --> Level01(Level 01)

  Level01 --> Level01Materials([Materials])
  Level01 --> Level01Meshes([Meshes])
  Level01 --> Level01Textures([Textures])

  Scripts --> EnemiesScripts([Enemies])
  EnemiesScripts --> TankScripts([Tank])
  EnemiesScripts --> RobotScripts([Robot])

  UI --> HUD([HUD])
  UI --> Menus([Menus])

  HUD --> HUDTextures([Textures])
  Menus --> MenusTextures([Textures])

  %% Weapons --> Gun([Guns])
  %% Weapons --> Shotgun([Shotguns])
 
  %% Gun --> GunMaterials([Materials])
  %% Gun --> GunMeshes([...])

  %% Shotgun --> ShotgunMaterials([Materials])
  %% Shotgun --> ShotgunMeshes([...])

  style Character fill:#90EE90,stroke:green
  style Enemies fill:#FFD580,stroke:orange
  style Weapons fill:#F08080,stroke:red