= Desarrollo de Videojuegos 3D: Cinemáticas inversas
Jesús Torres <jmtorres@ull.es>
include::../config/attributes.adoc[]
:imagesdir: {imagesdir}/ik
2019-2020

Para animar un personaje hacen falta dos cosas: una malla y un esqueleto.
La animación se debe a la rotación de los ángulos de las uniones de los huesos del esqueleto, lo que cambia la postura del esqueleto, mientras la malla se deforma para seguirlo
La posición final de cualquier miembro del esqueleto se puede determinar fácilmente al conocer los ángulos de rotación de las uniones y la posición relativa de unas uniones respecto a otras —definidas por los huesos del esqueleto—.
A este cálculo se lo conoce como cinemática directa.

Pero a veces, para dar más realismo a la escena, nos interesa hacerlo a la inversa.
Por ejemplo, que al poner el personaje los pies en el suelo, se ajusten los ángulos de rotación de las uniones para que el personaje parezca apoyarse con normalidad, aunque la superficie sea irregular.
A esto se lo conoce como cinemática inversa o IK —del inglés _inverse kinematic_—.


En Unity para Para IK hace falta Humanoid rig:
Ver los detalles de optimización de la animación:
https://unity3d.com/how-to/unity-best-practices-for-engine-performance?_ga=2.199834286.1017864420.1581032515-2049087233.1564526278