= Desarrollo de Videojuegos 3D: Arquitectura de software
Jesús Torres <jmtorres@ull.es>
include::../version.adoc[]
Curso {academic-year}
include::../../config/attributes.adoc[]
include::enlaces.adoc[]
include::footnotes.adoc[]
include::docstats.adoc[]

ifdef::backend-pdf[]
[preamble]
== Arquitectura de software
endif::[]
[TIME]
====
*Tiempo de lectura:* {document-reading-time}
====

El desarrollo de un videojuego, como el de cualquier otro programa, puede convertirse en infierno si:

* Primero no nos sentamos a diseñar una arquitectura de software adecuada, antes de lanzarnos a programar.

* A la hora de resolver los problemas que surjan, no optamos por soluciones preestablecidas y conocidas en la comunidad de desarrolladores.

* No dedicamos tiempo a hacer tests.

* No seguimos buenas prácticas de diseño y de programación, como por ejemplo S.O.L.I.D., Clean Code<<Martin2012>> o Clean Architecture<<Martin2017>>.

A continuación, haremos un resumen de algunas buenas prácticas y consejos que deberíamos tener presentes mientras diseñamos y desarrollamos el software de nuestros juegos.

== Arquitectura basada en componentes

Lo primero que debemos tener en cuenta es que muchos motores de videojuegos, entre los que se incluyen Unity y Unreal Engine, han adoptado por una arquitectura basada en componentes —también llamada Entidad-Componente (EC)—.
Eso significa que cuanto más adoptemos esa arquitectura en el desarrollo de nuestros juegos, más ergonómico nos parecerá el motor que utilicemos.

En Unity los objetos o entidades de una escena se llaman _GameObjects_ y les podemos agregar componentes.
Esa agregación de componentes que se comunican entre sí es lo que determina las funcionalidades de cada objeto.
De hecho, un objeto sin componentes —si tal cosa fuera posible, porque en Unity el componente *Transform* no se puede eliminar— no tiene ninguna funcionalidad en absoluto.

Y lo mismo ocurre en Unreal Engine, solo que las entidades de la escena se llaman _actores_ que, al igual que en Unity, reciben su funcionalidad por medio de los componentes que se le añadan.
Quizás la principal diferencia entre un motor y el otro, en este aspecto, es que en Unreal Engine los componentes se pueden agregar en una jerarquía de componentes —es decir, unos componentes pueden ser hijos de otros— mientras que en Unity eso no es posible.
En Unity, son los _GameObjects_ los que se organizan en una jerarquía de objetos.

Pensar en términos de programación orientada a componentes no es sencillo para quienes aterrizamos desde la programación orientada a objetos tradicional, donde lo común es construir jerarquías inmensas de clases en un esfuerzo por asegurar la reutilización del código y evitar repetirnos.
Pero, como veremos, este cambio de mentalidad no es un capricho de los diseñadores de motores de videojuegos.

=== Componentes frente a herencia

Supongamos que estamos desarrollando una serie de NPC{blank}footnote:[{fn-npc}] para nuestro juego.
Como es habitual, tendrán un controlador de IA y un nivel de salud.
Así que esas características comunes las implementamos en la clase `Entity` para no repetir código.

De `Entity` se heredan para crear cada uno de los tipos de personaje: guerreros con espada, hechiceros, arqueros y hechiceros con espada.
Y, además, hay versiones con la IA normal y otras con una IA más agresiva.
Un posible esquema UML de relación entre las clases se puede ver en la <<fig-herencia-uml>>, donde, por ejemplo, la flecha de SwordFightingEntity a Entity indica que la primera extiende —es decir, hereda— de la segunda.

[[fig-herencia-uml]]
.Ejemplo del uso de herencia para crear distintos tipos de NPC.
include::diagrams/herencia_uml.adoc[]

Al ver la <<fig-herencia-uml>> parece evidente que mientras más características queramos combinar más complejo es el esquema de relación.
Si, por ejemplo, hubieran distintas formas de ser afectados por el daño, todas las clases tendrán una clase derivada con una versión con esa nueva forma de sufrir daño.
Si hubiera otro tipo de IA, todas las clases tendrán una nueva versión con el nuevo tipo de IA.

Lo peor de todo es que en la <<fig-herencia-uml>> se ve que no se puede evitar la repetición de código.
Por ejemplo, `MagicAndSwordFightingEntity` hereda de `SwordFightingEntity`, así que la primera puede aprovechar el código de la segunda para el combate con espada, pero no hereda de `MagicFightingEntity`, así que el código para el combate con magia no se reutiliza.
Hay que volver a escribirlo para esta clase donde se combinan ambos tipos de combate.

NOTE: En {cpp} y otros lenguajes de programación, una clase puede heredar de múltiples clases base, pero esto no suele ser una solución ya que conlleva otros problemas (véase el {diamond-problem}[problema del diamante]).

La solución a este problema es utilizar componentes, cada uno de los cuales aportan alguna característica a la entidad.

[[fig-componentes-uml]]
.Ejemplo del uso de composición para crear distintos tipos de NPC.
include::diagrams/componentes_uml.adoc[]

En la <<fig-componentes-uml>> se puede observar como ahora cada entidad recibe características según los componentes que se le agreguen.
Cada componente se puede reutilizar en varias entidades al mismo tiempo y para añadir nuevas características —como una IA diferente o una nueva forma de recibir daño— solo necesitamos crear un nuevo componente y añadirlo a la entidad que queramos.

=== Conclusión

En definitiva, la programación orientada a componentes es una herramienta muy potente en el desarrollo de videojuegos.
Solo tenemos que adquirir el esquema mental adecuado para utilizarla correctamente.
Pensar en los objetos —_GameObjects_, actores o entidades— que necesitamos, las características que debe tener cada uno y qué componentes necesitamos para dotar a los objetos de esas características.

Esto no significa que debamos rechazar completamente la herencia y de otras características típicas de la programación orientada a objetos, ya que son herramientas complementarias.

Es muy posible tengamos tipos de componente, es decir, componentes que dotan el objeto de cierta funcionalidad, solo que de forma diferente.
Por ejemplo, componentes para implementar distintas formas de desplazamiento: nadando, andando, en un vehículo, etc.
En ese caso es evidente que el uso de la herencia con respecto a una clase base nos facilita compartir fácilmente código común.
Incluso, aunque no exista ese código común, se puede heredar de una interfaz, para que el resto del código dependa de la abstracción del componente y no de implementaciones concretas.

También es frecuente que detrás de los objetos y componentes del juego necesitemos todo un conjunto de sistemas que se desarrollan completamente desacoplados del motor, lo que nos permite implementarlos como mejor consideremos y reutilizarlos fácilmente.
Por ejemplo, sistemas de inventario, de _crafting_ o de habilidades, algoritmos para trazar rutas, trayectorias o incluso simular sistemas económicos complejos, librerías de serialización de objetos o de comunicación en red, entre muchas otras posibilidades.

== Los principios de diseño S.O.L.I.D.

Una solución muy común entre aquellos que se aproximan a motores como Unity o Unreal Engine es la que se representa en la <<fig-anti-solid>>.

[#fig-anti-solid]
.Ejemplo de un mal uso de la composición.
include::diagrams/anti_solid.adoc[]

En la <<fig-anti-solid>> todos los NPC necesitan un solo componente `NPCFightingController` que lo sabe hacer todo.
Implementa diferentes tipos de combate, de formas de recibir daño, de comportamientos de inteligencia artificial, etc.
Se supone que la elección de unas opciones u otras para cada entidad se toma por medio de variables, seguramente configurables desde el editor.

Es fantástico aprender lo suficiente como para ser capaces de meter todo junto en una sola clase de, seguramente, 1000 líneas de código o más.
Pero lo que no vemos es que cada vez va a ser más difícil añadir características nuevas y que seguramente seamos los únicos del equipo del proyecto que vamos a entender el código.
Y eso si no lo dejamos aparcado mucho tiempo.
En unas semanas, seguramente tampoco nosotros sepamos retomarlo.

Al diseñar nuestros componentes y nuestras clases —dado que cada componente es una clase— una regla básica a respetar es el _Principio de responsabilidad única_: La noción de que una clase solo debería tener una única responsabilidad.

Es evidente que el diseño de la <<fig-anti-solid>> no cumple eso pero, al menos a priori, mientras que el de la <<fig-componentes-uml>> sí lo hace.

=== El resto de principios S.O.L.I.D.

El _Principio de responsabilidad única_ es el primero de una serie de principios de diseño de software llamados S.O.L.I.D, que deberíamos tener siempre muy presentes y que enumeramos a continuación:

. *Principio de responsabilidad única*.
La noción de que una clase o componente solo debería tener una única responsabilidad.

. *Principio abierto/cerrado*.
La noción de que las entidades de software deben estar abiertas para su extensión pero cerradas para su modificación.
Esto se traduce en la recomendación de usar interfaces y clases abstractas de las que heredar para desarrollar implementaciones concretas.

. *Principio de sustitución de Liskov*.
La noción de que los objetos de un programa deben poder ser reemplazables por instancias de clases derivadas sin alterar el correcto funcionamiento del programa.

. *Principio de segregación de la interfaz*.
La noción de que tener muchas interfaces específicas, para cosas concretas, es mucho mejor que tener una única interfaz de propósito general que sirva para todo.
+
Este principio nos sugiere que no siempre debemos tener una interfaz para cada tipo de componente, sino que es posible que distintas funcionalidades puedan abstraerse en diferentes interfaces.
Luego podemos elegir si cada interfaz se implementa en un componente diferente o si, por el motivo que sea, es mejor que un componente implemente varias de estas interfaces.

. *Principio de inversión de la dependencia*.
La noción de que se debe depender de abstracciones en lugar de depender de implementaciones.
Lo que básicamente indica que a las clases se les deberían inyectar sus dependencias como interfaces.

[NOTE]
====
Aunque algunos desarrolladores, para respetar este principio, corren a utilizar _frameworks_ de inyección de dependencias, lo cierto es que en muchos casos no suelen hacer falta.

Los motores basados en componentes ofrecen una API para que un componente pueda ganar acceso a otros componentes del mismo u otro objeto de la escena.
Esto es, en sí mismo, un mecanismo para inyectar dependencias en los componentes.
====

En realidad es complicado entender estos 5 principios sin ver ejemplos completos.
Por eso merece la pena dedicarle un rato al siguiente vídeo, dónde en la primera mitad se explica la aplicación de los principios S.O.L.I.D. al desarrollo en Unity.

.Conferencia "S.O.L.I.D. Unity" en Unite Austin 2017.
video::eIf3-aDTOOA[youtube, opts="modest", width=854, height=480]

=== Más allá de S.O.L.I.D.

Lo primero para asimilar estos principios es intentar aplicarlos en nuestros propios proyectos.
Es decir, detenernos un momento antes de comenzar a programar, pensar en el problema que tenemos entre manos y cómo lo vamos a resolver y diseñar las clases y los componentes.

Es recomendable dedicar algo de tiempo a asimilar y poner en práctica las reglas y principios del _clean code_<<Martin2012>>.
Lo podemos hacer leyendo el libro o alguno de los múltiples resúmenes disponibles en Internet, como <<Perez2020>> y <<Altadill>>.
Posteriormente, se puede seguir profundizando de la mano de Clean Architecture<<Martin2017>>, donde se siguen los principios S.O.L.I.D. para definir patrones arquitecturales con los que crear software flexible y mantenible.

Hay muchos otros patrones arquitecturales de moda, como: _Hexagonal Architecture_, _Domain-Driven Development_ u _Onion Architecture_.
Aunque, pocos son fácilmente aplicables al desarrollo de videojuegos, pueden ser útiles para desarrollar servicios de apoyo, como: registro y autenticación de usuarios, _matchmaking_, clasificación o tienda de accesorios, entre otros.

Un patrón que si puede ser interesante estudiar e intentar aplicar, porque está sonando bastante en la industria, es Entidad-Componente-Sistema —o _Entity-Component-System_ (ECS), en inglés—.
ECS ofrece un gran desacople entre componentes —de tal forma que varios equipos pueden trabajar en cualquier sistema de forma independiente— y facilita el desarrollo orientado a datos, lo que bien aprovechado debe ofrecer mayor rendimiento.
ECS es una de las ideas centrales de {unity-dots}[Unity DOTS], la gran apuesta de Unity para modernizar completamente el motor y las herramientas de Unity.

== Managers, Controladores y Sistemas

Si cada componente debe tener una única responsabilidad es complicado que pueda cumplir su cometido sin cooperar con otros componentes, excepto para funcionalidades muy sencillas.

Imaginemos por un momento que una funcionalidad de nuestro juego es disponer de un inventario con las siguientes características:

* En cada nivel hay objetos que pueden ser recogidos, añadidos al inventario y utilizados, cuando llegue el momento.

* Cada personaje tiene su inventario.

* Algunos objetos del inventario de los personajes se pueden caer y pueden ser recogidos por otro personaje.

[[fig-inventory-system]]
.Ejemplo de sistema de inventario.
include::diagrams/inventory_system.adoc[]

Esto se podría resolver añadiendo un componente a cada objeto que puede pertenecer al inventario y otro a cada personaje que tiene un inventario donde almacenar objetos.
En la <<fig-inventory-system>> al primero lo hemos llamado `InventoryItem` y al segundo `InventoryManager`
Ambos tipos de componentes trabajan de forma coordinada para implementar un _sistema de inventario_.

=== Sistemas

Un sistema es una combinación de componentes de software que trabajan juntos para implementar cierta funcionalidad.
En un videojuego suelen haber múltiples sistemas: inventario, locomoción, salvado, meteorología, conducción, _spawn_{blank}footnote:[{fn-spawn-system}], interfaz de usuario, etc.

[TIP]
====
En Unity es muy recomendable el uso de espacios de nombres para agrupar los componentes de los distintos sistemas.
Los espacios de nombre proporcionan límites bien definidos entre sistemas, evidenciando, gracias al uso de las cláusulas `using` cuándo un sistema depende de otro.
Eso ayuda a pensar si esas dependencias son necesarias o hace falta pensar mejor el diseño.

En {cpp} el uso de espacios de nombres también es una buena práctica, pero el *UnrealHeaderTool* de Unreal Engine no los soporta.
Eso significa que en Unreal Engine se pueden usar espacios de nombres con el código {cpp} puro, pero no con el código heredado de `UObject` que interactúa con el motor y el editor.
En su lugar se pueden agrupar diferentes sistemas en distintos módulos y _plugins_.
Unreal Engine recomienda esta vía para modularizar el código que extiende el editor y las funcionalidades del motor, pero conviene sopesarlo bien para el código de _gameplay_ porque obliga a lidiar con mayor frecuencia con las interfaces entre módulos. 
====

=== Manager

Los _managers_ gestionan una colección de entidades.
Por ejemplo, NPC, proyectiles, enemigos, cámaras, sistemas de partículas, etc.
Para mejorar el rendimiento, pueden almacenar los objetos en un _pool_ de objetos para reusarlos rápidamente.

Los _managers_ también facilitan encontrar rápidamente todos los objetos de cierto tipo, evitando usar las funciones de búsqueda del motor —como las funciones `FindXXXXXX()` en Unity— que son más lentas.
Por ejemplo, es buena idea tener un `CameraManager` que permita conocer las cámaras existentes y obtener rápidamente una referencia a la cámara activa.
En Unity se puede usar `camera.main` para conocer la cámara activa, pero esta propiedad usa la función `FindGameObjectsWithTag()`, lo que es más lento que tener un _manager_ con una referencia a la cámara.
De igual forma, en juegos multijugador, es buena idea tener en la escena un `PlayerManager` a quien preguntarle por todos los jugadores conocidos, en lugar de pedirle al motor que los busque de entre todos los objetos de la escena.

[TIP]
====
Se pueden usar _managers_ para gestionar de forma centralizada componentes que son de uso común, aunque no sean entidades.
Por ejemplo, en videojuegos es muy frecuente el uso de temporizadores, pero algunos motores —como Unity— no traen clases y funciones específicas para gestionarlos.
Esto puede hacer que se implemente una y otra vez la misma funcionalidad en distintos _GameObjects_, usando _timestamps_ y el método `Update()`.
Por eso es buena idea implementar un _manager_ de temporizadores, que se encargue de la creación y manipulación de los temporizadores que necesite la aplicación, evitando repetir una y otra vez el mismo código y separando mejor las responsabilidades.
====

// TODO: Hacer una posible implementación.

Aunque por lo comentado pueda parecer que de cada tipo de _manager_ solo hay uno en cada escena, lo cierto es que no es así.
En la <<fig-inventory-system>> se puede observar como cada personaje que puede llevar `InventoryItem` tiene su componente `InventoryManager`.
En general, no parece interesante conocer y gestionar de forma centralizada todos los `InventoryItem` de la escena, sino que cada personaje lo gestione en su _manager_.

=== Game Manager

El _game manager_ es un tipo especial de manager dedicado a llevar el flujo del juego: carga de escenas y transiciones, modos de pausa y de menús, etc.

En los juegos pequeños puede ser responsable de centralizar otros aspectos del estado del juego, como: puntuaciones, vidas, aparición de enemigos y jugadores, etc.
Pero en juegos grandes es mejor separar esas responsabilidades en otros componentes.

=== Controlador

Un controlador es un componente que va en una entidad específica y sirve para orquestar varios componentes de la entidad o controlar la entidad por completo.

En la <<fig-inventory-system>>, `PlayerController`, `Weapon` y `AIController` son controladores.
Y si tuviéramos proyectiles seguramente también tendrían que tener su controlador, encargado de disparar, mover, causar daño y destruir la entidad al final de su recorrido.

Un ejemplo típico de controlador es el `PlayerController`, cuya función es controlar todos los aspectos del personaje del jugador.
En función de la complejidad del juego, el `PlayerController` puede implementar toda la funcionalidad o —algo mucho mejor— esta puede estar repartida en controladores más pequeños: `LocomotionController` —encargado del a dónde queremos ir y cómo llegar— `AnimationController` —estados de animación y controlar los _blends_— `StatsController` —encargado de las estadísticas del personaje— o el `InputController` —responsable de leer la entrada de un jugador—.
Incluso el `LocomotionController` puede repartir su funcionalidad en varios controladores, si existen varios modos de movimiento: a pie, nadar o escalada; activando un controlador u otro según el modo de cada momento.
Todos estos controladores diferentes funcionan orquestados por el `PlayerController`.

=== Componentes cuando es necesario

Aunque desarrollemos pensando en una arquitectura basada en componentes, lo cierto es que no todo tiene que ser implementado como componentes del motor.

Fundamentalmente existen dos motivos para implementar una funcionalidad como un componente del motor —en Unity, heredando de MonoBehaviour— y no como una clase convencional:

. Que para implementar la funcionalidad necesitemos alguno de los eventos que el motor envía a los componentes, como eventos de colisión, _trigger_ o de actualización del frame.

. Que sea conveniente que su configuración sea accesible a los diseñadores a través del editor.

Si no se da ninguno de los casos anteriores, deberíamos plantearnos implementar la funcionalidad en una clase convencional.
Las clases convencionales son más sencillas y rápidas de testear, ya que no hace falta ejecutar el juego para probarlas.
Basta con crear un test que aisle el componente y lo pruebe, usando algún _framework_ de pruebas de software.

Volvamos, por un momento, al sistema de inventario de la <<fig-inventory-system>>.
¿Realmente los `InventoryManager` necesitan de alguna funcionalidad especial a la que solo tendrían acceso siendo componentes?
Probablemente no.
Seguramente no sean más que listas en las que añadir y eliminar unos cuantos `InventoryItem`.

El motivo para que hayamos decidido implementar los `InventoryManager` como componentes es porque queremos que los diseñadores puedan decidir qué entidades los tienen y configurarlos a su criterio.
Pero eso se puede resolver separando la creación y configuración del `InventoryManager` del `InventoryManager` en si mismo.

[[fig-inventory-system-plus]]
.Ejemplo de sistema de inventario «mejorado».
include::diagrams/inventory_system_plus.adoc[]

En la <<fig-inventory-system-plus>> los personajes tienen un componente `Inventory` que los dota de inventario.
Pero ese componente no implementa el _manager_ del inventario, sino que su función es crear el _manager_ e inicializarlo con los elementos que el diseñador indique en la configuración del componente en el editor.
El _manager_ del inventario es `InventoryManager`, que es una clase convencional.
Cada `Inventory` tiene un campo, `InventoryManager` con una referencia al objeto de su _manager_ de inventario.

La ventaja es que así las clases `InventoryManager` e `InventoryItem` se pueden testear mediante test unitarios, sin tener que ejecutar el juego para hacerlo.

== Unreal Engine Gameplay Framework

Los motores de videojuegos ofrecen los servicios básicos que puede necesitar cualquier aplicación multimedia interactiva: _render_, iluminación, lectura de la entrada de usuario, creación de interfaz de usuario, físicas, efectos visuales, sistema de animación, gestión de recursos, carga de escenas, etc.
Algunos ofrecen por encima un _framework_ con componentes de uso frecuente en el desarrollo del _gameplay_ de cualquier juego, en parte prescribiendo la forma de crear nuevos sistemas y la arquitectura del juego.

Unreal Engine trae un _gameplay framework_ muy orientado al tipo de juegos que hace Epic Game —videojuegos de acción competitivos en primera o tercera persona— que incluye algunos de los componentes que hemos comentado hasta el momento<<UE-Game-Framework>>.
A continuación veremos qué componentes son y cómo se relacionan con lo que conocemos.
Esto nos puede ofrecer ideas que podemos trasladar a otros otros motores, como Unity, donde debemos implementar nuestro propio _gameplay framework_ atendiendo al tipo de juegos que queramos hacer.

=== GameMode y GameState

En el _gameplay framework_ de Unreal Engine el trabajo del _game manager_ se divide entre estas dos clases:

* *GameMode*.
Contiene el código con las reglas del juego, como por ejemplo: el control del flujo del juego, las transiciones entre niveles, el número de jugadores, las condiciones para ganar, las reglas para hacer aparecer o reaparecer a los jugadores, cuándo se puede pausar el juego y qué ocurre cuando se pide, etc.

* *GameState*.
Almacena los datos que describen el estado del juego: puntuaciones, lista de jugadores, objetivos cumplidos, etc.

El motivo para separar ambas aspectos del _game manager_ en clases diferentes es que facilitar el guardado del estado del juego —por ejemplo, al salvar la partida— y la sincronización en juegos multijugador online:

* Si estamos haciendo un juego multijugador online, la lógica del juego debe ejecutarse únicamente en el servidor para evitar las trampas.
Los datos del juego confiables también deben almacenarse en el servidor, pero al mismo tiempo es necesario mantener una copia sincronizada en cada cliente.
Eso es exactamente lo que hace Unreal Engine con *GameMode*, *GameState* y *PlayerState*.

* Incluso si el juego no es en red, lo más normal es tener algún mecanismo de salvado de la partida.
Separar la lógica del juego de los datos facilita poder almacenar estos últimos para salvar 
y recuperar el estado del juego.

TIP: *GameMode* implementa el comportamiento esperable de un juego multijugador competitivo.
Si se trabaja en otro tipo de juego, es mejor heredar de *GameModeBase*, que también es la clase base de *GameMode*.

No se recomienda guardar directamente en *GameState* datos específicos de cada jugador —como el nombre, el nivel de salud o la puntuación específica de cada jugador— sino solo datos generales del estado del juego.
*GameState* gestiona una instancia de *PlayerState* para cada jugador, que es donde se deben almacenar los datos específicos de cada uno.
El *PlayerState* de cada jugador también es accesible a través del actor del personaje, como veremos más adelante.

==== GameMode como configurador del juego

En *GameMode* podemos añadir propiedades para configurar diferentes características globales del juego.
Entre la propiedades que trae *GameMode* por defecto están las clases que se van instanciar para implementar diferentes aspectos del juego relacionados con el _gameplay framework_: *GameState*, *PlayerController*, *PlayerState*, *HUD* o *DefaultPawn*.
Así, por ejemplo, se puede cambiar en el *GameMode* las propiedades:

* *DefaultPawn*, para indicar nuestro propio actor del personaje del jugador.

* *PlayerState*, para indicar la clase que guardará los datos específicos de cada jugador.

* *HUD*, para configurar la clase con la interfaz del juego.

Al trasladar estas ideas a otros motores debemos considerar la forma de trabajar con ellos para trasladarlas.
Por ejemplo, en Unity la propiedad equivalente a *DefaultPawn* puede guardar una referencia al _prefab_ del personaje, que incluiría tanto los componentes que le dan su aspecto visual y animación, como el componente que hace de *PlayerController*.
Con el *HUD* se puede hacer exactamente lo mismo —referenciar un _prefab_ que será instanciado por el _game manager_— aunque existe otra opción muy común, dado que facilita la separación de ámbitos: construir el HUD en una escena aparte y que el _game manager_ la cargue de forma aditiva cuando haga falta.
En este caso la propiedad del _game manager_ haría referencia al nombre o al índice de la escena que contiene el HUD.
Además el _game manager_ puede cachear una referencia al controlador de la interfaz de usuario —nombrada `UIController`, por ejemplo— para que otros componentes puedan localizarlo rápidamente, si les hace falta, sin usar métodos `FindXXXXXX()`.

=== PlayerController y AIController

En Unreal Engine se llama *Controller* al actor responsable de controlar un personaje.
Es decir, el personaje y su controlador son actores diferentes, mientras que en Unity lo habitual es que el controlador sea un componente del _GameObject_ del personaje.

En la terminología de Unreal Engine se dice que cuando un *Controller* comienza a controlar un personaje, es que lo «posee». 

En el _gameplay framework_ hay dos clases que heredan de *Controller*:

* *PlayerController*.
Controla el personaje según las órdenes del jugador.
Es decir, lee la entrada del jugador y cambia el estado del personaje en base a ella.

* *AIController*.
Se usa cuando el control del personaje proviene de la IA.

Todo actor que puede ser poseído por un controlador debe heredar de *Pawn*, que ofrece una interfaz mínima común para ser controlarlo.
Tanto *PlayerController* como *AIController* controlan el personaje usando dicha interfaz.
Esto es interesante porque significa que los controladores son intercambiables.
Cualquier personaje puede ser controlado fácilmente por la IA o por el jugador, en cualquier momento del juego.
Obviamente, si añadimos características adicionales a nuestros personajes, tendremos que extender nuestros controladores para que las utilicen.

==== PlayerController

Un *PlayerController* es creado por *GameMode* para cada jugador, generalmente a través del método `Login()`.

Para gestionar la entrada del usuario, los actores pueden crear durante el juego un *InputComponent*, usado para relacionar eventos de entrada con métodos del actor o de componentes del actor.
Es en estos métodos donde implementamos las acciones que correspondan a cada evento, permitiendo que cualquier actor pueda responder a la entrada del jugador.
Los *InputComponents* se registran en una pila de *InputComponents* gestionada por el *PlayerController*, que a su vez indica a *PlayerInput* que lea los eventos de entrada y los procese.
Para ello, *PlayerInput* lee los eventos de entrada y los entrega a los *InputComponents* en el orden determinado por la pila.
Los *InputComponents* puede «consumir» el evento de entrada, haciendo que sea ignorado por componentes posteriores en la pila.

El *PlayerController* también gestiona lo que denomina la rotación del control.
La idea es separar la rotación del personaje en la escena —que es una propiedad del actor del personaje— y la orientación de la cámara, de la rotación del control del jugador.
Esto sirve, por ejemplo, para poder apuntar en una dirección, mientras el personaje está orientado en otra para desplazarse.

Otras de las responsabilidades del *PlayerController* es crear el actor que gestiona la cámara —llamado *PlayerCameraManager*— y el HUD. 
Las clases de ambos actores se pueden configurar en las propiedades del *PlayerController*.

[NOTE]
====
La clase HUD del _gameplay framework_, a la que se hace referencia en las propiedades del *GameMode* y en el *PlayerController*, es realmente un concepto antiguo.

Sigue existiendo porque es un actor que da acceso a un lienzo {ue-ucanvas}[*UCanvas*] con el que se puede dibujar directamente en la pantalla.
Hay quien lo usa para para dibujar su propia interfaz de usuario o para mostrar información de depuración con métodos como `DrawText()`.
En la actualidad, es mucho mejor crear _widgets_ con UMG y mostrarlos usando `AddToViewport()` en el método `BeginPlay()` del *PlayerController*.
====

Conectar cámara y HUD con el *PlayerController* es muy útil en los juegos multijugador dónde se juega con la pantalla partida.
El equivalente en Unity sería, por ejemplo, que el componente *PlayerController* coordinará a otros dos componentes del mismo _GameObject_ del personaje del jugador: `CameraController` e `UIController`.
Estos pueden ser configurados con el _prefab_ de la cámara y de la interfaz de usuario, respectivamente, y hacerse responsables de instanciarlos, configurarlos —porque, por ejemplo, el _canvas_ de la interfaz debe saber en qué cámara le corresponde mostrarse— y gestionarlos durante el juego.

=== Pawn y Character

*Pawn* es la clase base de todos los actores que pueden interactuar con el mundo y ser controlados por el jugador o por la IA, mediante un *Controller*.
Se puede usar para implementar personajes muy básicos, no necesariamente humanoides.

El _gameplay framework_ incluye los siguientes *Pawn*:

* El *DefaultPawn* extiende *Pawn* añadiendo un _collider_ esférico y un *StaticMesh*.
Se puede mover libremente en 3D, sin ser afectado por la gravedad.

* El *SpectatorPawn* extiende *DefaultPawn* para ofrecer la funcionalidad de espectador de la partida.

*Character* también extiende *Pawn*, pero para añadirle todo lo que necesita un personaje tradicional: una cápsula de colisión, un *SkeletalMeshComponent* —es decir, una malla que puede ser animada mediante el sistema de animación de Unreal Engine— y un *CharacterMovementComponent*, que implementa modos de movimiento típicos como: caminar, correr, saltar, volar y nadar.

TIP: El código del *CharacterMovementComponent* puede ser muy ilustrativo sobre cómo hacer nuestro propio controlador de movimiento —que podemos llamar `LocomotionController` o `MovementController`— de un personaje en cualquier otro motor.
En Unity el *CharacterController* es bastante simple, por lo que muchas veces acaba teniendo que ser sustituido por una implementación propia o comprada en la _Asset Store_.

Las clases *Pawn* y *Character* exponen la interfaz necesaria para que un *Controller* los controle para, por ejemplo, desplazarlos por la escena.
Los *Controller* que «poseen» un *Pawn* o *Character* reciben muchos de los eventos que llegan a dicho *Pawn*, lo que les permite redefinir el comportamiento del actor mientras está poseído.

*Pawn* también ofrece la API *Damage*, que se usa para causar distintos tipos de daño —puntual, radial u otro que definamos— en el personaje, registrando quién es el causante.
Además, Unreal Engine ofrece el componente *ProjectileMovementComponent*, diseñado para dotar a cualquier actor del tipo de movimiento característico de un proyectil.

En la arquitectura descrita puede surgir la duda de si colocar el código que procesa los eventos de entrada del usuario para manejar el personaje en el *PlayerController* o en el *Pawn* del personaje del jugador.
La ventaja del utilizar el *PlayerController* es que facilita desacoplar la entrada de las acciones y habilidades de cada personaje.
Los *Pawn* pueden exponer una interfaz común con acciones posibles, que en cada uno se pueden implementar de forma diferente y que pueden ser controladas indistintamente por el jugador, mediante un *PlayerController*, o por la IA, mediante un *AIController*.
El *PlayerController* —que en juegos en red solo existe en el cliente del jugador— solo tiene la responsabilidad de procesar los eventos de entrada para llamar a la acción adecuada del personaje poseído.
En cualquier caso, si un personaje necesita algún tipo de entrada especial, siempre es posible procesarla directamente en el *Pawn* de dicho personaje.

=== PlayerState y otros datos del jugador

En Unreal Engine —así como en Unity y en otros motores— el lugar recomendado para almacenar datos específicos del jugador es el actor / entidad / objeto del personaje del jugador.
En el caso particular de Unreal Engine, el *Pawn* poseído por un jugador devuelve una instancia del *PlayerState* del jugador a través del método `GetPlayerState()`.

Cada *PlayerState* es un actor, básicamente porque así debe ser para que sea replicado en los diferentes clientes en juegos multijugador online.
Esto quiere decir que es útil para guardar información del jugador que queremos que sea accesible al resto de jugadores de la partida —como la salud o la puntuación—.

Para almacenar datos que el resto de jugadores no necesitan conocer —como el inventario o la cantidad de munición— se puede usar una estructura de datos referenciada desde el propio *Pawn* del personaje o el *PlayerController*.
Aunque referenciar esta información desde el *Pawn* del personaje parece lo más intuitivo —ya que son posesiones o características del personaje— en Unreal Engine es común usar el *PlayerController*, ya que este objeto solo existe en el cliente del jugador.
Como en el caso de *GameState* y *PlayerState*, puede ser interesante que estos datos estén separados en un objeto diferente, aunque accesible desde el personaje o el *PlayerController*, para facilitar su almacenamiento y recuperación.

.Ejemplo general de persistencia de datos del jugador.
include::diagrams/playerdata.adoc[]

=== Level Blueprint

Aunque no está relacionado con el _gameplay framework_, merece la pena señalar que cada nivel en Unreal Engine tiene un *Level Blueprint* donde escribir código global del nivel.

En otros motores esto se asemeja a tener un _level manager_.
Por ejemplo, en Unity es bastante común tener en cada escena un _GameObject_ con un componente *LevelManager* con el código y propiedades globales del nivel.

=== Gameplay Framework

En la <<fig-ue-gameplay-framework>> se puede observar un esquema del _gameplay framework_ de Unreal Engine que hemos comentado en apartados anteriores.

[[fig-ue-gameplay-framework]]
.Esquema del _gameplay framework_ de Unreal Engine.
include::diagrams/ue_gameplay_framework.adoc[]

Esta arquitectura se puede trasladar fácilmente a otros motores, con las modificaciones que mejor se adapten a nuestras necesidades, si tenemos la necesidad de crear nuestro propio _framework_.
Por ejemplo, para juegos de un solo jugador seguramente nos resulte más sencillo gestionar el controlador de la interfaz de usuario y el _manager_ de la cámara desde el _game manager_ que desde *PlayerController*.

== Patrones de diseño

Una vez tenemos clara la arquitectura, con los componentes y sistemas que necesitamos, llega la hora de implementarlos.
Durante ese proceso seguramente surgirán una serie de problemas a los que tendremos que buscar solución.
Por suerte, es probable que no necesitemos inventar nada nuevo, porque hay quienes ha recopilado los problemas que aparecen una y otra vez durante el desarrollo de diferentes proyectos de software en la forma de _patrones de diseño de software_.

Hay muchos patrones, así que nosotros nos centraremos fundamentalmente en aquellos que nos puedan ser más útiles en el desarrollo de videojuegos.

=== Singleton

Al hablar de los _managers_ hemos visto que en muchos casos solo nos hace falta una instancia de algunos de ellos.
Es decir, puede que `InventoryManager` necesitemos uno por jugador, pero `GameManager`, `ParticleManager`, `AudioManager` o `CameraManager` seguramente sólo necesitaremos uno en cada nivel o, incluso, uno durante todo el juego.

Eso es precisamente lo que nos asegura el patrón _singleton_<<Wikipedia-Singleton>>, que de una clase solo existirá un único objeto accesible a todo el resto del código.

En <<Wikipedia-Singleton>> hay algunos ejemplos de implementaciones del patrón _singleton_ en diferentes lenguajes.
Entre ellos {cpp} y C#.
Sin embargo, los motores de videojuegos pueden hacer algunas recomendaciones respecto a su uso.

==== Singleton en Unreal Engine

En Unreal Engine se recomienda ignorar los _singleton_.
En su lugar, es preferible extender alguna de las múltiples clases de actores dedicados a estados y lógica global del juego:

* *GameMode*, donde se establecen las reglas del juego.

* *GameState*, donde se almacena la información global del estado del juego.

* *GameInstance*, que se usa para el resto del estado y lógica global del juego que no encaje en las clases anteriores.
La forma adecuada de usar *GameInstance* es heredar de `UGameInstance` —para incorporar el código de {cpp}— y luego heredar de esta clase en _blueprint_ para facilitar la configuración de propiedades.

Obviamente, hay que tener mucho cuidado estructurando el código porque *GameInstance* solo hay una en el juego, para toda la lógica y los datos que queremos meter ahí.

==== Singleton en Unity

En Unity el problema es que la clase `MonoBehaviour` de la que deben heredar todos los componentes no nos permite impedir que se creen múltiples instancias de la clase.
El mecanismo usado en <<Wikipedia-Singleton>> para C# —que consiste en hacer el constructor privado— no funciona con clases derivadas de `MonoBehaviour`.
De hecho, `MonoBehaviour` hace privado el constructor para sus propios fines.

Así que hay que optar por otras soluciones.
Una de las más completas sería la siguiente clase `Singleton`, de la que podríamos derivar nuestros _managers singleton_:

[source,csharp]
----
public class Singleton : MonoBehaviour
{
    private static Singleton _instance; <1>

    public static Singleton Instance <2>
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType<Singleton>(); <3>
                if (_instance == null)
                {
                    var gameObject = new GameObject();
                    _instance = gameObject.AddComponent<Singleton>(); <4>
                }
            }

            return _instance;
        }
    }

    private void Awake()
    {
        DontDestroyOnLoad(this); <5>
    }
}
----
<1> `+_instance+` se define como `static` para que sea un campo compartido por todas las instancias de las clase `Singleton`. La idea es que aquí se guarde una referencia a la primera de estas instancias, que es la única que al final debe existir.
<2> Como `+_instance+` es privado, otras partes del código accederán a la instancia del _singleton_ usando esta propiedad de la siguiente manera: `Singleton.Instance`.
<3> Al acceder se comprueba si ya existe una instancia.
Si no es así, se busca el primer `GameObject` con el componente `Singleton` y se guarda su referencia en `+_instance+`.
<4> Si no se encontrase ningún objeto con el componente `Singleton`, se crea uno, se añade el componente `Singleton` y esta es la instancia que se guarda en `+_instance+` y que se devuelve desde la propiedad.
<5> Se le indica a Unity que no destruya el objeto cuando cargue una nueva escena que sustituya a esta.
Esto solo es necesario cuando nos interese ese comportamiento, por ejemplo, para tener un mismo _game manager_ durante toda la ejecución del juego.

El código anterior es una guía de cómo hacer que una clase cualquiera sea un _singleton_.
Si estamos creando un *AudioManager*, el componente seguramente se llamará `AudioManager` —no `Singleton`— y eso tendremos que tenerlo en cuenta al adaptar el código.

Para evitar escribir una y otra vez este mismo código en todos y cada unos de nuestros _singleton_, podemos crear una clase genérica:

[source,csharp]
----
public class Singleton<T> : MonoBehaviour
{
    private static T _instance;

    public static T Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType<T>();
                if (_instance == null)
                {
                    var gameObject = new GameObject();
                    _instance = gameObject.AddComponent<T>();
                }
            }

            return _instance;
        }
    }

    private void Awake()
    {
        DontDestroyOnLoad(this);
    }
}
----

Y heredar de ella cada vez que necesitemos un _singleton_.
Por ejemplo:

[source,csharp]
----
public class AudioManager : Singleton<AudioManager>
{
    // ...
}
----

Lo cierto es que este ejemplo anterior es algo complejo porque hace algunas cosas por nosotros.
Una de las que menos me convence es crear el objeto si no existe y añadir el componente, porque generalmente preferimos añadirlo nosotros manualmente a la escena para configurar algún campo desde el editor.
Otra cuestión es que al implementarlo así, se deja en manos de cualquier parte del código llamar a la propiedad `Instance`, con lo que se crea automáticamente un objeto que a lo mejor no está en la escena porque no debería hacer falta, siendo mejor detectar el error.

Así que puede que en ocasiones nos interese utilizar una versión más simple:

[source,csharp]
----
public class Singleton : MonoBehaviour
{
    public static Singleton Instance { get; private set }

    private void Awake()
    {
        if (Instance != null)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(this);
    }
}
----

Ahora es responsabilidad nuestra crear un objeto vacío en la escena, añadir el componente y, donde lo necesitemos, obtenerlo con Singleton.Instance.
Lo que sí nos asegura el código anterior es que nunca habrán dos _GameObject_ con el mismo componente, incluso si cargamos en algún momento otra escena que tenga el mismo componente.

==== Criterios de uso

Algunos desarrolladores consideran el _singleton_ como un anti-patrón, pues se utiliza frecuentemente en situaciones donde no es necesario, con el inconveniente de introducir un objeto con estado global en la aplicación, por lo que tienden a evitarlos.

Antes de usarlo es importante asegurarse de que no existe otra opción, por ejemplo, comprobando primero la siguiente lista de criterios:

. Que sea absolutamente necesario que solo haya una instancia de la clase.

. Que deba ser accesible a todo el resto del código.

. Que el objetivo de usarlo sea controlar el acceso concurrente a un recurso.

Los _managers_ que se utilizan para gestionar colecciones de entidades —generalmente empleando un _pool_ de objetos— suelen encajar en los 3 criterios anteriores.

==== Instanciar antes de la primera escena

Los _singleton_ se añaden en _GameObjects_ en las escenas donde se vayan a usar.
Aquellos que deban perdurar durante toda la ejecución del juego —como puede ser el _game manager_— se deben incluir en la primera escena.
Gracias al uso de la sentencia `DontDestroyOnLoad(this)` se evita su destrucción al cargar otras escenas durante el flujo del juego.

Sin embargo, puede que en algún caso interese instanciar un _singleton_ —o ejecutar cualquier otro código— antes de cargar la primera escena y que se activen los primeros _GameObjects_.
En ese caso se deben etiquetar los métodos estáticos con el código que se quiere ejecutar con el atributo `RuntimeInitializeOnLoadMethod`:

.Ejemplo de método que instancia el _game manager_ antes de cargar la primera escena.
[source,csharp]
----
public class Bootstrapper
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void Initialize()
    {
        InstanceGameManger();
    }
}
----

Si se va a instanciar algún _GameObjects_ se puede hacer directamente mediante código de C#, por ejemplo, o cargando un _prefab_ preconfigurado guardando en la carpeta `Resources` del proyecto.

.Ejemplo de cargar un _prefab_ antes de cargar la primera escena.
[source,csharp]
----
public class Bootstrapper
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void Initialize()
    {
        InstanceGameManger();
    }

    private void InstanceGameManger()
    {
        var gameObject = GameObject.Instantiate(Resources.Load("Init"));
        gameObject.name = "[GameManager]";
    }
}
----

El parámetro `RuntimeInitializeLoadType.BeforeSceneLoad` de `RuntimeInitializeOnLoadMethod()` indica el momento de la carga en el que debe ejecutarse el método<<Unity-RuntimeInitializeLoadType>>.

.Domain Reloading
****
Al ejecutar el juego en el editor, Unity resetea el estado de los _scripts_.
En proyectos grandes eso puede llegar a consumir bastante tiempo, haciendo que según va creciendo el proyecto cada vez sea más difícil iterar rápidamente entre programar y probar, durante el desarrollo del proyecto.

El _Domain Reloading_ —que es cómo se llama este mecanismo— se puede desactivar.
Pero entonces es necesario modificar el proyecto para que los campos y eventos _static_ se reseteen adecuadamente al ejecutar el juego.
El cómo hacerlo está perfectamente explicado en la documentación de Unity<<Unity-Domain-Reloading>>.
****

=== State

El patrón _state_ se utiliza cuando se busca que el comportamiento de un objeto cambie dependiendo de un estado interno<<Wikipedia-State>>.
Las máquinas de estados finitos —o FSM, del inglés _Finite-State Machine_— que en videojuegos son de gran utilidad, pueden implementarse con este patrón<<Wikipedia-FSM>>.

[[fig-game-state-machine]]
.Esquema típico de los estados de cualquier juego.
[plantuml, format="svg"]
----
hide empty description
[*] --> Intro
Intro -> Menu : Intro Ends
Menu -> Loading : Play Clicked
Loading -> Play : Scene Loading Finished
Play -> Pause : ESC Pressed
Pause -> Play : Play Clicked
Pause -> Loading : Restart Clicked
Pause -> Menu : "Go to Menu" Clicked
----

Las máquinas de estados finitos son muy utilizadas para implementar la inteligencia artificial de los NPC, pero también tienen muchos otros uso en un videojuego:

* En los sistemas de animación que incorporan los motores de videojuegos, para seleccionar la animación que debe reproducirse en cada momento.

* En los controladores de los personajes, para gestionar el estado del personaje: modo de desplazamiento, estados durante el combate, estado de alerta, _combos_, etc.

* En el _game manager_ para gestionar el modo en el que se encuentra el juego en cada momento: intro, menú principal, jugando, pausa, etc.
En la <<fig-game-state-machine>> se puede observar un esquema típico de lo que podrían ser los estados de cualquier juego.

El siguiente código ejemplifica una implementación bastante sencilla de máquina de estados:

.Ejemplo de implementación de máquina de estados.
[source,csharp]
----
public interface IState <1>
{
    void OnEnter();
    void OnExit();
    IState Tick();
}

public class StateTransition <2>
{
    public readonly IState From;
    public readonly IState To;
    public readonly Func<bool> Condition;

    public StateTransition(IState from, IState to, Func<bool> condition)
    {
        From = from;
        To = to;
        Condition = condition;
    }
}

public class StateMachine <3>
{
    public IState CurrentState { get; private set; } <4>

    private List<StateTransition> _stateTransitions = new List<StateTransition>();
    private List<StateTransition> _anyStateTransitions = new List<StateTransition>();

    public void AddAnyTransition(IState state, Func<bool> condition)
    {
        var stateTransition = new StateTransition(null, state, condition);
        _anyStateTransitions.Add(stateTransition);
    }

    public void AddTransition(IState from, IState to, Func<bool> condition)
    {
        var stateTransition = new StateTransition(from, to, condition);
        _stateTransitions.Add(stateTransition);
    }

    public void SetState(IState state)
    {
        if (CurrentState == state)
            return;

        CurrentState?.OnExit();
        CurrentState = state;
        CurrentState?.OnEnter();
    }

    public void Tick() <5>
    {
        if (CurrentState == null) return;
        
        var transition = CheckForTransition();
        if (transition != null)
        {
            SetState(transition.To);
            return;
        }

        var nextState = CurrentState.Tick();
        if (nextState != null)
        {
            SetState(nextState);
        }
    }

    private StateTransition CheckForTransition()
    {
        foreach (var transition in _stateTransitions)
        {
            if (transition.From == CurrentState && transition.Condition())
                return transition;
        }

        foreach (var transition in _anyStateTransitions)
        {
            if (transition.Condition())
                return transition;
        }

        return null;
    }
}
----
<1> Interfaz para las clases que implementan los estados.
El método `OnEnter()` se ejecuta al entrar en el estado y `OnExit()` al salir y cambiar a otro estado.
`Tick()` se ejecuta cada _frame_ y puede provocar una transición devolviendo el próximo estado.

<2> Clase que describe una transición.
Sus campos guardan el estado origen y destino de la transición y una función que será evaluada en cada _frame_ y debe devolver `true` si se dan las condiciones para cambiar de estado.
<3> Clase de la máquina de estados.
<4> Estado actual de la máquina de estados.

<5> El componente que utiliza `StateMachine` debe llamar a `Tick()` en cada _frame_ para:
. Comprobar las transiciones y cambiar de estado si la condición de alguna se cumple
. Llamar al método `Tick()` del estado actual.

Es fácil encontrar en Internet implementaciones de máquinas de estados, algunas mucho más completas, con características adicionales.
Para problemas realmente complejos, probablemente necesitaríamos una máquina de estados jerárquica, donde cada estado puede tener a su vez su propia máquina de estados.

Las corrutinas —de las que hablaremos en el <<_corrutinas>>— también son una forma implícita de implementar máquinas de estados.
Si nuestro entorno de desarrollo soporta corrutinas, elegir entre usar estas o una implementación explícita de máquina de estados como la anterior, depende del caso.
Las corrutinas no son gratis, pero hasta que se detecta un problema de rendimiento, lo mejor es escoger la solución que sea más legible y más fácil de mantener para cada problema.

=== Factory

El patrón _factory_ se utiliza para construir objetos.
Pero ¿por qué utilizar un patrón para construir objetos si todos las clases tienen un constructor?

. Porque hay objetos que pueden ser complejos de construir.
Una clase se supone que ya ha sido creada para que asuma cierta responsabilidad, por lo que por el principio de responsabilidad única puede ser interesante colocar en otro sitio la responsabilidad de construir adecuadamente sus instancias.

. Para que la dependencia entre clases sea débil.
Un objeto puede tener dependencias de otros objetos.
Cuando estos otros objetos se instancian en el constructor de la clase del primero se crea un acoplamiento que dificulta poder reutilizar y extender el código.
Por ejemplo, si la clase NPC instancia desde su constructor la clase que implementa la IA, más adelante puede ser complicado reutilizar la clase del NPC para crear entidades que utilicen otra IA.

En la <<fig-npc-factory>> se puede observar cómo el patrón _factory_ consiste en utilizar una clase o función _factory_ para construir los NPC y los componentes de los que depende.

[[fig-npc-factory]]
.Ejemplo del patrón _factory_ aplicado a crear NPC.
include::diagrams/npc_factory.adoc[]

En la <<fig-npc-factory>> el `NPCFactory` tiene un método  `CreateSimpleNPC()` que crea NPC con una IA simple llamada `SimpleAIBrain`.
Si se quisiera crear un NPC con otro tipo de IA, sólo haría falta añadir otro método a `NPCFactory` que creara un NPC con componentes diferentes.

Las clases _factory_ son como cualquier tipo de clase.
Es decir, pueden crearse heredando de una clase base, si queremos que tengan una interfaz común.
Por ejemplo, en un proyecto complejo con cientos de tipos de objetos podemos tener una clase _factory_ para cada uno, que herede de una clase común. 
Esto facilita crear un catálogo de _factories_, al que podemos pedirle en cualquier momento la _factory_ adecuada para el siguiente objeto que queramos crear.

[[fig-abstract-factory]]
.Ejemplo del patrón _abstract factory_ para crear un catálogo de clases _factory_.
include::diagrams/abstract_factory.adoc[]

A esta variante del patrón _factory_ se la denomina _abstract factory_<<Wikipedia-Abstract-Factory>>.

=== Strategy

El patrón _strategy_ ofrece una forma de seleccionar dinámicamente algoritmos y asignarlos a un objeto en tiempo de ejecución, para que resuelva cierta tarea o tenga cierto comportamiento.

Un ejemplo sería si tuviéramos proyectiles guiados que pueden dirigirse a su destino por tres mecanismos: calor, sonar o ubicación exacta.
Si todos los proyectiles se simulan de la misma manera y lo único que cambia es su sistema de guiado, no parece sensato implementar tres clases diferentes solo por esa pequeña diferencia.
En su lugar podemos tener una clase `Projectile` y tres estrategias: `SeekWithHeat`, `SeekWithSonar` y `SeekToFixedLocation`

[[fig-strategy-pattern]]
.Ejemplo del patrón _strategy_ con proyectiles guiados.
include::diagrams/strategy_pattern.adoc[]

Este patrón encaja muy bien con el sistema de componentes de los motores de videojuegos.
Es decir, `Projectile` podría ser un componente controlador y cada estrategia una clase convencional referenciada en el componente.
Pero también sería posible que cada estrategia fuera un componente de la entidad, de tal forma que `Projectile` buscaría el primer componente `ISeekBehaviour` y lo usaría como estrategia.

Teniendo esto en cuenta, el patrón _strategy_ también puede ser interesante en la implementación de cómo se desplaza un personaje.
Supongamos que el personaje del jugador tiene un `PlayerController` que orquesta los distintos controladores presentes: `LocomotionController`, `AnimationController`, etc.
El `LocomotionController` es el responsable de cómo se desplaza el personaje, que puede hacerlo de diferentes maneras: caminar, esquiar, escalar, nadar, etc.
Estos modos se pueden implementar directamente en el código del `LocomotionController`, usando _ifs_ para determinar cuándo se ejecuta el código de unos u otros.
Sin embargo, es mucho mejor utilizar el patrón _strategy_ para implementarlos en sus propias clases y activarlos en el `LocomotionController` según lo adecuado para cada momento.

Igual que comentamos antes, cada uno de estos modos podría ser una clase convencional —referenciada en el `LocomotionController`— u otro componente en la entidad del personaje.
En este último caso, `LocomotionController` se asegurara de que sólo uno de ellos esta activo en cada momento, imponiendo su modo de desplazamiento al movimiento del personaje.

=== Decorator

El patrón _strategy_ permite cambiar la implementación de un componente dinámicamente, pero ¿qué ocurre si no queremos cambiar completamente la implementación sino solo mejorarla temporalmente?
Por ejemplo, los personajes pueden llevar distintos atuendos, entre ellos una ropa de camuflaje que hace que sea más difícil de ver.
O las armas pueden llevar silenciador —con lo que no hacen ruido— o miras —con lo que aumenta la precisión—.

En cualquiera de estos casos no parece que lo adecuado sea hacer una implementación nueva para cada una de las variantes, sino extender la que ya existen sin modificarla.
Eso es exactamente lo que permite el patrón _decorator_<<Wikipedia-Decorator>>.

En la <<fig-decorator-pattern>> se puede observar un ejemplo de cómo podría usarse el patrón _decorator_ para modificar las características de una pistola básica, según los accesorios que le incorporemos: un estabilizador o un silenciador.

[[fig-decorator-pattern]]
.Ejemplo del patrón _decorator_ con una pistola.
include::diagrams/decorator_pattern.adoc[]

Toda pistola tiene unos valores de precisión y ruido —tal y como indica la interfaz `IGun`— que pueden ser diferentes para cada tipo de arma.
Los decoradores heredan de `GunDecorator`, que a su vez hereda de `IGun`, por lo que cada decorador presenta la misma interfaz que cualquier otra pistola.

Lo que hacen los decoradores es envolver el objeto de la pistola a la que afectan para obtener una nueva pistola con propiedades modificadas.
Como cada pistola modificada también hereda de `IGun`, se pueden incorporar varios decoradores a una misma pistola, acumulando el efecto de todos ellos.

=== Visitor

El patrón _visitor_ se usa cuando queremos realizar una acción en un objeto pero no queremos implementar la lógica en el propio objeto porque semánticamente no sería lo correcto, tal vez porque implicaría que el objeto tendría que asumir más responsabilidad de la que consideramos que le corresponde.
Así que preferimos tener un objeto externo que «viste» el objeto y realice la acción correspondiente<<Wikipedia-Visitor>>.

Por ejemplo, supongamos que cada personaje dañable implementa un componente `Damageable` que aplica el daño adecuado en el nivel de salud al llamar a su método `TakeDamage()`.
Ahora bien, pueden haber diferente tipos de ataque y distintos personajes con diferentes características a los que se aplica distinto nivel de daño.
Incluso puede que el daño no se limite al nivel de salud, sino que también pueda afectar a la resistencia, nivel de defensa o de energía.
Que el componente `Damageable` no solo tenga que aplicar el daño sino calcularlo para cada posible combinación, puede hacer que el componente se vuelva realmente complejo y difícil de mantener.

La solución con el patrón _visitor_ es que cada ataque sea un visitante que aplique el daño que corresponda sobre el objeto visitado.
Así la responsabilidad de calcular y aplicar el daño se reparte entre las clases de los distintos tipos de ataque.

[[fig-visitor-pattern]]
.Ejemplo del patrón _visitor_ con el daño de los ataques.
include::diagrams/visitor_pattern.adoc[]

En la <<fig-visitor-pattern>> se puede ver un ejemplo donde cada arma implementa la interfaz `IVisitor` y los personajes dañables la interfaz `IDamageable`.
Cada arma tiene un método `ApplyDamage()` para cada tipo de personaje, de tal forma que en cada uno se implementa cómo ese tipo de arma daña a ese tipo de personaje en particular.

=== Pool de objetos

El _pool_ de objetos es probablemente uno de los patrones que más suenan en el desarrollo de videojuegos.
Consiste en un contenedor de objetos pre-reservados en la memoria, que pueden ser extraídos cuando haga falta y vueltos a añadir en la colección cuando se ha terminado con ellos.
El objetivo es reutilizar los objetos, evitando el coste de instanciar y destruir objetos repetidamente, limitando las posibilidades de sufrir retrasos que afecten a la experiencia.

[[fig-object-pool-pattern]]
.Ejemplo del _pool_ de objetos con proyectiles.
include::diagrams/object_pool_pattern.adoc[]

En la <<fig-object-pool-pattern>> vemos un posible caso de uso.
La entidad `Weapon` tiene un componente `ProjectileLauncher` especializado en disparar proyectiles.
Pero como al mismo tiempo pueden haber múltiples entidades con `ProjectileLauncher`, cada una no gestiona sus proyectiles, sino que delega en el _singleton_ `ProjectileManager` que, a su vez, utiliza un _pool_ de objetos para reutilizar rápidamente los objetos utilizados por todos los `ProjectileLauncher` del juego.

NOTE: Los _pool_ de objetos son siempre útiles, aunque son especialmente interesantes en dispositivos móviles, que están más limitados en recursos que muchos PC y consolas.

Los tipos de objetos susceptibles de ser gestionados en un _pool_ son aquellos de los que esperamos tener que disponer cierta cantidad rápidamente durante la ejecución del juego.
Por ejemplo: sistemas de partículas, proyectiles o enemigos.
Es el _manager_ de cada uno de estos tipos de objetos el que debe utilizar un _pool_ como contenedor para gestionar internamente de forma eficiente su colección.

En Internet existen cientos de versiones de _pool_ de objetos.
Una implementación para Unity muy sencilla, con la que entender fácilmente la idea, es la de <<Contreras2019>>.

[TIP]
====
Hay varios aspectos en los que tal vez se podría mejorar <<Contreras2019>>.
Uno es que el _pool_ almacena directamente _GameObjects_, cuando quizás sería más interesante que guardará el objeto por el componente que gestiona el _manager_ —como `Projectile`, en el ejemplo anterior—.
En ese caso, sería ideal que la clase fuera genérica para facilitar la reutilización de la implementación.

El otro aspecto es que seguramente sería mejor utilizar como contenedor `Stack` en lugar de `Queue`, ya que ofrece mejor {localidad-referencia}[localidad de referencia].
Es decir, previsible se aprovechan mejor las memorias caché al reutilizar primero los objetos usados más recientemente.
====

=== Observer

El principal objetivo del patrón _observer_ es permitir a unos objetos observar cambios en el estado interno de otros objetos<<Wikipedia-Observer>>, sin que los segundos tengan que saber nada de los primeros.

Suele implementarse usando un mecanismo por el cual los objetos pueden definir señales o eventos a emitir cuando algo cambia.
Otros objetos del programa pueden suscribirse en cualquier momento a cualquiera de esos eventos, indicando el método que debe ser llamado cuando el evento es emitido.

Por ejemplo, el jugador puede tener una propiedad con su nivel de salud y un evento para notificar cuando ese valor ha cambiado.
A ese evento puede suscribirse la barra de salud.
Así, cuando el nivel de salud cambia, la barra de salud es notificada.
Esta solo tendrá que leer la propiedad del jugador con el nivel de salud y actualizar el estado de la barra de acuerdo a dicho valor.
En contraposición, si es la barra de salud la que pregunta periódicamente por la salud del jugador, se dice que hace _polling_.

Cuando los eventos ocurren esporádicamente —como cambios de salud o la muerte de un personaje— el patrón _observer_ es bastante cómodo y eficaz.
Sin embargo, para eventos que ocurren con mucha frecuencia —por ejemplo, casi cada _frame_— el _polling_ suele ser más eficaz; especialmente porque el componente que necesita la información puede controlar la frecuencia con la que la pide según sus necesidades.

==== Eventos en Unity

C# en Unity soporta los conceptos de delegado y evento, que son muy útiles para implementar este patrón.

Un delegado es una referencia a un método<<Microsoft-Delegates>>.
Se puede pasar como argumento a un método y guardarlo en los campos de una clase.
Luego el código de la clase puede invocar el método en el delegado para obtener información externa a demanda o para notificar un suceso —por ejemplo, haber completado una tarea o un error—.

.Ejemplo de declaración y uso de un delegado.
[source,csharp]
----
public class DelegateUseSample
{
    // ...
    
    public delegate int PerformCalculation(int x, int y); <1>
    
    // ...

    public void Compute(int x, int y, PerformCalculation callback) <2>
    {
        // ...

        PerformCalculation performCalculation = callback; <2>

        // ...

        int result = performCalculation(x, y); <3>
    }
}

// ...

public int Add(int x, int y)
{
    return x + y;
}

// ...

var sample = new DelegateUseSample();
sample.Compute(10, 20, Add); <2>
----
<1> Declaración del delegado `PerformCalculation`.
`PerformCalculation` ahora es un tipo que se puede usar para declarar variables y campos en los que se puede guardar una referencia a un método que tenga exactamente los mismos argumentos de entrada y de salida.

<2> Los métodos pueden recibir la referencia y guardarla en una variable local o en un campo de la clase.
En el ejemplo se guarda el delegado en el argumento `callback` en la variable local `performCalculation`.

<3> Cuando es necesario, se llama al método referenciado.

C# y Unity también soportan eventos.
Cada evento es un objeto que contiene una lista de delegados con referencias a métodos de otros objetos que se han suscrito a dicho evento<<Microsoft-Events>>.
Un objeto se puede suscribir y desuscribir en cualquier momento de un evento.
Cuando el objeto que tiene el evento quiere notificar un suceso, lo que hace es emitir el evento.
Puesto que los eventos pueden invocar a múltiples suscriptores, no se permite que tengan un valor de retorno.

.Ejemplo de declaración de un evento en C#.
[source,csharp]
----
public class EventUseSample
{
    // ...
    
    public delegate void OnCompleteDelegate(int result); <1>
    
    public event OnCompleteDelegate OnComplete; <2>

    // ...
}
----
<1> Primero se declara el delegado `OnCompleteDelegate` que admite el evento.
Como hemos comentado, el delegado no puede tener valor de retorno.

<2> Después se declara el evento `OnComplete` usando el delegado `OnCompleteDelegate`.

En Unity se soportan dos mecanismos: eventos de C# y *UnityEvent*.
Por lo general los desarrolladores prefieren los primeros, ya que son nativos de C#, son algo más rápidos y consumen menos memoria cuando solo hay un suscriptor.
Sin embargo, *UnityEvent* tiene algunas ventajas importantes<<Dunstan2016>>:

* Los objetos *UnityEvent* se pueden serializar, por lo que se pueden configurar desde el editor.
Por eso son ideales cuando queremos que los diseñadores puedan configurarlos.

* Los eventos de C# reservan y liberal memoria al añadir y eliminar suscriptores al evento, reservando más cuantos más suscriptores hay.
Esto quiere decir que no es buena idea usarlo con listas grandes de suscriptores, especialmente si previsiblemente se van a suscribir y desuscribir frecuentemente en cada _frame_.

* Si se usan eventos de C#, es importante recordar que los objetos deben desuscribirse al destruirse, en el método `OnDestroy()`.
De lo contrario, el evento mantendrá una referencia al objeto suscripto, por lo que la memoria no será liberada por el recolector de basura de Unity.

==== Eventos en Unreal Engine

El concepto de puntero a función de C y {cpp} es más primitivo pero similar al de delegado en C#.
Aun así, Unreal Engine ha desarrollado soluciones prácticamente equivalentes a las que hemos comentado para C#.

* *Delegado* simple<<UE-Delegates>>.
Son tipos de objetos que pueden guardar una referencia a una función, método o función lambda.
Se pueden usar en clases y _structs_ que no sean `UCLASS`, se pueden copiar, pasar por valor como argumento de funciones y, si guardan una referencia a un método de un `UObject`, lo hace como una referencia débil al objeto.
Es decir, que el delegado sabe si el objeto ha sido destruido antes de usar la referencia, pero esta no cuenta para evitar su reciclado por parte del recolector de basura.

* *Delegado _multi-cast_*<<UE-Multicast-Delegates>>.
Tiene las mismas características que los *delegados simples*, pero puede guardar múltiples referencias a distintas funciones y métodos al mismo tiempo, lo que permite usarlos para notificar un evento a múltiples objetos.
Como ocurre con los eventos de C#, no pueden tener valor de retorno.

* *Evento*<<UE-Events>>.
Tiene las mismas características que los *delegados _multi-cast_*, pero solo la clase que declara el evento puede emitirlo.
Es decir, que una clase puede exponer el evento con seguridad en su interfaz pública, sabiendo que cualquier otro objeto puede suscribirse, pero solo ella podrá emitirlo. 

* *Delegado dinámico*<<UE-Dynamic-Delegates>>.
Internamente guarda la referencia a los métodos registrados sin usar punteros, sino mediante el identificador del objeto y el nombre de la función.
Eso significa que cuando se invoca el delegado, tiene que consultar al sistema de reflexión de Unreal Engine la dirección en la memoria de los métodos registrados para llamarlos.
Por lo tanto, son más lentos que otros tipos de delegado y necesita que los métodos registrados hayan sido marcados como `UFUNCTION()`, pero tienen la ventaja que pueden ser serializados para ser almacenados y configurados en el editor.
También permiten indicar el método que queremos suscribir simplemente usando una cadena con su nombre.
+
Los delegados dinámicos existen tanto en versión simple como _multi-cast_

En _blueprints_ se utilizan eventos y *Event Dispatcher*<<UE-Event-Dispatchers>>.
Los métodos marcados en {cpp} como `BlueprintNativeEvent` o `BlueprintImplementableEvent` se exponen en _blueprint_ como eventos.
Mientras que los *delegados dinámicos _multi-cast_* se exponen como *Event Dispatchers*.

=== Event Bus

Un bus de eventos o _event bus_ es un objeto que hace de concentrador central de todos los eventos del juego.
Las clases se registran en el bus de eventos para ser informadas de los eventos que le interesan.
Cuando una clase emite un evento, lo hace inyectándolo en el _bus de eventos_, que lo retransmite a las clases que hayan registrado su interés en ese evento en concreto.

[[fig-event-bus-pattern]]
.Diagrama de secuencia de ejemplo del patrón _event bus_.
include::diagrams/event_bus_pattern.adoc[]

El motivo para usar este patrón es desacoplar todo lo posible las clases.
Unas emiten eventos y otras consumen esos eventos, pero no tienen que conocerse las unas a las otras, porque los objetos se suscriben a los eventos sin conocer quién los emite.
Mientras que en el patrón _observer_ un objeto si tienen que tener referencias a los objetos cuyos eventos quieren recibir.

Obviamente el mayor desacople entre componentes también puede presentar algunos inconvenientes:

* Peor rendimiento y probablemente mayor consumo de memoria.
En general no es buena idea usar el _event bus_ para notificar sucesos a los que se debe responder inmediatamente, desde métodos ejecutados cada _frame_, como: `Update()`, `Tick()` o `TickComponent()`.

* Hace complicado tener una idea de la interrelación entre componentes y de quién atiende qué eventos.

* Es más complejo que otras soluciones.
Por ejemplo, con el patrón _observer_ el código es más pequeño y simple y usa menos abstracciones.

=== Humble Object

Hemos comentado anteriormente que los componentes son complejos de testear porque implica correr los test con el motor de videojuegos ejecutándose, lo que es bastante lento.
La idea detrás del patrón _humble object_ es poner la lógica de nuestros componentes en una clase normal, que podamos testear rápidamente sin el el motor, usando un _framework_ de testeo convencional.
Para usar esa clase en el juego, solo hace falta crear una envoltura alrededor de la clase que permita usarla como un componente; siendo esa envoltura lo que denominamos _humble object_.

El objetivo es reducir la cantidad de código allí donde la lógica del juego entra en contacto con la interfaz del motor de videojuegos, porque generalmente ese código es más difícil de testear.

[[fig-humble-object-pattern]]
.Ejemplo del patrón _humble object_ con el controlador de proyectiles en Unity.
include::diagrams/humble_object_pattern.adoc[]

Por ejemplo, en Unity seguramente la lógica del controlador de un proyectil necesite el evento `Update()` de `MonoBehaviour`.
Sin embargo, si implementamos esa lógica en una clase derivada de `MonoBehaviour` sería muy difícil de testear.

En su lugar, la lógica del controlador se puede implementar en una clase C# normal, con un método `Tick()` que se supone que debe ser llamado por "alguien" en cada fotograma.
Esta clase es sencilla de testear fuera del motor de videojuegos, porque no tendría ninguna dependencia de este último.
Después se crearía el componente —el _humble object_— heredando de MonoBehaviour, cuya única función es envolver el controlador para que pueda ser usado por el motor.
Así, cuando el motor llame al método `Update()` del _humble object_, este llamaría al método `Tick()` del controlador.

=== Flyweight

La idea del patrón _flyweight_ es que si el juego tiene muchos objetos similares, entonces es muy probable que podamos reducir el consumo de memoria —si nos hace falta— haciendo que los objetos compartan datos comunes.. 

Por ejemplo, en un nivel construido con vóxeles o cubos pueden usarse diferentes tipos de cubos —agua, tierra, hierba, roca o madera— con diferentes propiedades para cada tipo, como: color, material, dureza o si es navegable.
La aproximación tradicional implica que cada vóxel guarde los valores de sus propiedades, pero eso puede consumir una importante cantidad de memoria si el nivel es relativamente grande.
La alternativa es tener un objeto _flyweight_ para cada tipo de vóxel —con las propiedades correspondientes prefijadas— y que cada cubo simplemente guarde una referencia al objeto _flyweight_ de su tipo.
Obviamente, cada objeto vóxel seguirá teniendo que guardar datos únicos, como la posición en el espacio.

.Ejemplo del patrón _flyweight_ con vóxeles.
include::diagrams/flyweight_pattern.adoc[]

== Comunicación entre objetos

Atendiendo a los patrones y buenas prácticas descritas, vamos a comentar brevemente las formas más comunes en las que estructurar la comunicación de los objetos de la aplicación, con el objeto de pedir servicios o informar de cambios de estado.

=== Directamente

La comunicación directa es el caso más común.
Se usa cuando un objeto llama directamente a los métodos de otro.

Para que la comunicación directa sea posible es necesario que el objeto tenga una referencia al objeto con el que se quiere comunicar.
Estas referencias pueden ser obtenidas de diferentes maneras.
Por ejemplo, a través de los argumentos del constructor de la clase o de un método de inicialización, ya sea de forma manual —indicadas explícitamente desde el objeto que crea la instancia— o de forma automática —usando un inyector de dependencias—.

[NOTE]
====
En los motores que no permiten modificar los argumentos de los los constructores, para adaptarlos a nuestras necesidades, puede ser necesario incorporar un método de inicialización `Initialize()` a través del que pasar los parámetros y dependencias del nuevo objeto.

Es importante tener cuidado con esta situación ya que permite que un objeto sea creado y utilizado sin asegurar antes que ha sido inicializado correctamente —porque olvidamos llamar a `Initialize()`—.
Esto obliga a introducir comprobaciones adicionales en los métodos de la clase para prevenir errores por utilizarlos en objetos no inicializados adecuadamente.
====

Otra forma de que los objetos obtengan referencias a sus dependencias es por medio de _setters_, con los que objetos externos pueden alterar los campos privados que guardan dichas referencias.
Sin embargo, esto también permite que un objeto sea usado antes de ser inicializado correctamente. 

Finalmente, los objetos pueden usar métodos estilo `FindXXXXXX()` o `GetComponentXXXXXXX()`, proporcionados por algunos motores, para obtener las referencias que necesitan.
Dependiendo de la implementación, algunos de estos métodos pueden tener cierto coste.
Por lo que, si es así, lo recomendable es usarlos solo durante la inicialización o activación del objeto, guardando las referencias obtenidas para usarlas de forma eficiente durante la actualización del juego en cada _frame_.

En todo caso, es aconsejable usar interfaces en lo posible al establecer dependencias entre clases.
Así las clases dependen de abstracciones y no de implementaciones lo que, entre otras cosas, facilita el testeo.
Por ejemplo, si una clase depende de tener una referencia a un personaje solo para hacerle daño, no es recomendable que reciba la entidad del personaje o un tipo de componente concreto, sino la interfaz `IDamageable` que implementan todos los componentes que pueden aplicar daño a su personaje, ya que eso es todo lo que necesitan los objetos de la clase para hacer su trabajo.

=== Singleton

Cuando la comunicación es directa pero el objeto invocado se va a utilizar frecuentemente desde múltiples componentes de la aplicación, es posible que nos interese que dicho objeto sea un _singleton_.
Así la referencia a la instancia es muy sencilla de obtener, con solo conocer la clase.

Sin embargo, es importante recordar que los problemas de los _singleton_ son similares a los de las variables globales, por lo que es mejor limitar su uso.

=== Eventos

A veces conviene usar un mecanismo basado en eventos para comunicar los objetos, como es el caso de los patrones _observer_ y _event bus_.
El uso de eventos es especialmente interesante cuándo un objeto no sabe quién debe ser informado de algo.

El patrón _event bus_ tiene la ventaja adicional, respecto al patrón _observer_, de que quién recibe los eventos tampoco necesita conocer a quien los emite para suscribirse.
Como contrapartida es un patrón mucho más complejo de implementar que el patrón _observer_, es más complicado hacerse una idea de la interrelación entre componentes y de asegurar que un evento está alcanzando a todos los componentes a donde deben llegar.

[TIP]
====
En Unity existe la posibilidad de usar eventos estáticos de C#.
Los eventos estáticos existen antes de que se instancie un objeto de la clase por primera vez, por lo que es posible suscribirse a ellos sin esperar a que exista una instancia.
Solo es necesario conocer la clase.
Además, pueden ser invocados por cualquiera de las instancias de dicha clase.

Son interesantes porque permiten usar el patrón _observer_ incluso cuando un objeto no puede tener una referencia al objeto que los va a emitir para suscribirse.
====

== Corrutinas

La corrutina es un bloque de código similar a una función, con la diferencia de que puede suspenderse y reanudarse su ejecución varias veces antes de terminar.
Se trata de un patrón de concurrencia que resuelve el problema de realizar tareas de larga duración sin bloquear la ejecución de la aplicación<<Wikipedia-Corrutina>>.

Para ver cómo eso nos ayuda, reflexionemos por un momento en cómo se utiliza el método `Update()` de `MonoBehaviour` en Unity, ya que es uno de los motores que soporta corrutinas.
El método `Update()` se llama una vez para cada fotograma y en él no podemos hacer tareas de larga duración, porque si no salimos de `Update()` rápidamente el juego parecerá menos responsivo o incluso se quedará bloqueado.

Eso significa Si tuviéramos la idea de detectar un _combo_ como:

_«El ataque se iniciará si se pulsa kbd:[Z] y antes de 800 ms kbd:[X].
Si se inicia el _combo_, no podrá haber otro antes de 5 s»_

No podríamos implementarlo de forma sencilla en `Update()` porque si detectamos la pulsación de kbd:[A] no podemos esperar 800 ms comprobando si se pulsa kbd:[X] sin salir de `Update()`, pues durante ese tiempo el juego estaría completamente bloqueado.

La solución más común a este problema anterior es entrar en `Update()`, recordar en qué fase del _combo_ estamos, comprobar si se dan las condiciones para pasar a la siguiente fase y volver a salir.
Esto encaja perfectamente con el tipo de problemas que resuelven las máquinas de estados.
Sin embargo, con las corrutinas podemos programar esta tarea casi como en un único método convencional, sin utilizar máquinas de estados:

[source,csharp]
----
public IEnumerator ComboPressed(Action onComboDetected) <1>
{
    while(true) <2>
    {
        if (! Input.GetKeyDown(KeyCode.Z))
            return;

        float remainingTime = 0.8f; <3>
        while (remainingTime > 0f)
        {
            if (Input.GetKeyDown(KeyCode.X))
                onComboDetected(); <4>
                yield return new WaitForSeconds(5); <5>
            else <6>
                yield return null;
                remainingTime -= Time.deltaTime;
        }
    }
}
----
<1> Esta es la corrutina.
Es como una función convencional con sus argumentos.
En este caso el único argumento es la función que llamaremos si detectamos un _combo_, para que haga lo que corresponda.

<2> La corrutina iterará en un bucle infinito para solo tener que iniciarla una vez en el componente, llamando a `StartCorrutine(ComboPressed(OnComboDetected))`.

<3> Se ha detectado la pulsación de kbd:[Z], así que inicializamos el tiempo que le queda al jugador para pulsar kbd:[X] en `remainingTime`.

<4> Si se detecta la pulsación de kbd:[X], se llama a la función indicada en el argumento.

<5> Después la corrutina espera 5 segundos antes de continuar con su ejecución, iterando en el bucle y volviendo a esperar la pulsación de kbd:[Z].
+
Esto es «lo diferente» respecto a una función convencional.
El uso de `yield return` permite suspender la corrutina, para que su ejecución no continúe temporalmente.

<6> Si no se detecta la pulsación de kbd:[X], se suspende la corrutina temporalmente durante un fotograma y al volver se restará el tiempo transcurrido hasta el momento a `remainingTime`.
Cuando `remainingTime` sea 0, el bucle se rompe y se vuelve a esperar la pulsación de kbd:[Z].

[NOTE]
====
No se debe confundir las corrutinas con los hilos o con alguna otra técnica de paralelismo.
Las corrutinas parecen ejecutarse en paralelo, pero realmente se ejecutan secuencialmente en el hilo principal del proceso.
Así que no sirven para hacer tareas costosas en CPU repartiéndolas entre los núcleos del procesador.

Si se quiere hacer paralelismo en Unity, lo mejor es recurrir a su Jobs System<<Unity-Job-System>>.
Por su parte, Unreal Engine ofrece una solución similar a través de la clase `FQueuedThreadPool`<<UE-FQueuedThreadPool>>.
Ambas opciones implementan un patrón de concurrencia llamado _thread pool_.
====

=== Consideraciones sobre su uso

El ejemplo anterior es un caso muy simple, donde el uso de corrutinas brilla por su sencillez respecto a utilizar máquinas de estado.
Pero ¿qué ocurre si tuviéramos decenas de _combos_ con combinaciones más complejas y con parámetros ajustables por los diseñadores?
En ese caso, seguramente, una máquina de estado nos ofrecerían una solución más general y fácil de mantener.

Lo mismo ocurre en problemas similares donde se pueden emplear como sustitutas de las máquina de estados, como por ejemplo al implementar una IA.
Por lo general son una buena opción en casos simples. 

Las corrutinas también pueden ser muy útiles para controlar algunos efectos, como animaciones sencillas, vibraciones y pequeños desplazamientos —al estilo de lo que permiten paquetes como {dotween}[DOTween]—.
Sin embargo, no debemos olvidar que no son gratis, aunque usándolas de forma moderada eso no debe ser un problema<<Dunstan2015>>.

TIP: Crear objetos como `WaitForSeconds` para devolverlos con `yield return` da trabajo al _recolector de basura_ de Unity, por lo que es buena idea crearlos una vez y guardarlos para  reutilizarlos cuando haga falta.

Donde son más útiles las corrutinas es en operaciones asíncronas de larga duración, como: peticiones HTTP, lectura de archivos, carga de recursos o consultas a bases de datos.

=== Corrutinas de Unity frente a async/await

Desde C# 5.0 / .NET 4.5, C# tiene soporte nativo de corrutinas a través de las palabras clave async/await, pudiéndose utilizar en Unity desde Unity 2017.
Entonces ¿es mejor utilizar async/await que las corrutinas de Unity?

La recomendación es usar async/await para tareas relacionadas con la E/S, como peticiones HTTP, acceso a bases de datos y a archivos o para esperar la entrada del usuario cuadros de diálogo y otros elementos de interfaz de usuario.
Mientras que las corrutinas nativas de Unity son mejores para tareas que queremos lanzar en segundo plano y olvidarnos de ellas.

[[video-unity-async-vs-coroutines, {video-caption} {counter:video-number}]]
.{video-caption} {video-number}. Conferencia «Best practices: Async vs. coroutines» en Unite Copenhagen 2019.
video::7eKi6NKri6I[youtube, opts="modest", start=808, end=1662, width=854, height=480]

== Arquitectura de la interfaz de usuario

En el <<_observer>> comentamos el patrón _observer_ usando un ejemplo, que nos ayuda a resolver correctamente una duda común entre muchos desarrolladores noveles: ¿cosas como el nivel de salud o las vidas del jugador las debe tener el jugador o la propia barra de salud?
La respuesta es que los componentes de la interfaz de usuario no deben contener elementos del estado o de la lógica del juego, sino ser completamente independientes.

Usando el patrón _observer_, la lógica del juego puede notificar los cambios en el estado del juego mediante eventos y la interfaz de usuario puede estar suscrita a dichos eventos.
Sin embargo, incluso así existe cierto nivel de acoplamiento.
Por ejemplo, porque la barra de salud debe tener una referencia al objeto jugador para suscribirse al evento y, llegado el momento, leer el nivel de salud.

[[fig-ui-observer-sequence]]
.Interacción de la barra de salud con el personaje.
include::diagrams/ui_observer_sequence.adoc[]

El acople es aún mayor cuando la lógica del juego tiene que reaccionar a acciones en la interfaz de usuario —por ejemplo, en un sistema de diálogos— porque esto obliga a que los componentes de la lógica del juego conozca botones y menús para suscribirse a los eventos que puedan emitir.

Aunque pueda parecer que nada de esto no es un problema, lo cierto es que es muy difícil de mantener en juego grandes, con interfaces complejas.
Por eso es conveniente tomar algunas ideas de patrones arquitecturales usados comúnmente para desarrollar interfaces de usuario, como: Modelo-Vista-Presentación (MVP)<<Wikipedia-MVP>> o Modelo-Vista-ViewModel (MVVM)<<Wikipedia-MVVM>> y adaptarlas, para desacoplar mejor la interfaz de usuario de la lógica del juego.

=== Modelo-Vista-Presentación

En el patrón MVP<<Wikipedia-MVP>>:

* El _modelo_ es la interfaz que define los datos que se mostrarán o sobre los que actuará la interfaz de usuario.
En nuestro caso el modelo es el código de _gameplay_ del juego, ya que contienen los datos que se quieren mostrar y la lógica sobre la que se quieren actuar.

* El _presentador_ hace de intermediario entre el modelo y la vista, de tal forma que el modelo y la vista solo se comunican con el presentador.
Este recupera datos del modelo y los prepara para mostrarlos en la vista.

* La _vista_ es la interfaz de usuario en sí
Está formada por los controles y elementos visuales pasivos que muestran los datos del modelo y reciben las órdenes del usuario.

[[fig-mvp-en-videojuegos]]
.Esquema del patrón MVP.
include::diagrams/mvp_en_videojuegos.adoc[]

La vista puede contener la lógica necesaria para que los controles funcionen y para gestionar la navegación por la interfaz.
Los controles que ofrecen los motores suelen ser muy básicos, en comparación con los de cualquier _toolkit_ gráfico.
Así que a veces hace falta desarrollar controles más avanzados a partir de los controles básicos que proporcionan, como: cuadros de diálogo, barras de desplazamiento y paneles con _scroll_, barras de menú y menús desplegables, sistemas de navegación mediante pestañas o pila de paneles, entre otros. 

Todo ese código de la interfaz debe estar en la vista.
Así como aquel destinado a enriquecerla con animaciones y otros efectos.
Sin embargo, la interacción con el modelo y la preparación de los datos es manejada en exclusiva por el presentador.
Es el presentador el que se subscribe a los eventos del juego para actualizar la interfaz, al tiempo que está subscrito a los eventos de la interfaz para actuar sobre el _gameplay_.

=== Vista pasiva frente a controlador supervisor

En realidad la arquitectura MVP descrita y mostrada en la <<fig-mvp-en-videojuegos>> corresponde a una variante denominada _vista pasiva_.
Es interesante desde el punto de vista de facilitar la testabilidad, en tanto en cuanto para testear la mayor parte de la lógica de la interfaz de usuario basta con testear el presentador.
Pero algo compleja porque incluso los cambios más simples en la interfaz implican introducir en el presentador el código que la actualiza.

[[fig-mvp-sc-en-videojuegos]]
.Esquema del patrón MVP controlador supervisor.
include::diagrams/mvp_sc_en_videojuegos.adoc[]

En la otra variante —denominada _controlador supervisor_— la vista puede actualizarse directamente en los casos más simples a partir del modelo a través de un mecanismo de _data binding_ (véase el _<<_data_binding>>), sin intervención del presentador.
El presentador sigue siendo responsable de actualizar el modelo —en nuestro caso, actuar sobre el juego— y manipular la vista en los casos más complejos, que no puede resolverse por medio del _data binding_.

El _controlador supervisor_ normalmente necesita menos código que la _vista pasiva_, ya que los cambios más simples en la interfaz muchas veces se pueden resolver usando el mecanismo de _data binding_, sin tener que incluir código en el presentador.

=== Sobre el número de presentadores

Un error común al comenzar a trabajar con el patrón MVP es considerar que solo se necesita un presentador para la interfaz de usuario.
Sin embargo, lo lógico es que un juego tenga diferentes vistas, como: menú principal, HUD, sistema de inventario o sistema de diálogos; teniendo cada una su propio presentador.
Incluso algunos de estos elementos pueden ser lo bastante complejos como para que sea mejor descomponerlos en vistas diferentes, cada una con su presentador.
Por ejemplo, si tenemos un menú principal con submenús para configurar el juego o para iniciar una nueva partida.

[[fig-mvp-multi-presentador]]
.Esquema del patrón MVP multi-presentador.
include::diagrams/mvp_multi_presentador.adoc[]

=== Implementación de presentadores

En Unity el presentador puede ser un _GameObject_ con un componente —que, por ejemplo, podemos llamar `UIController`— que haga de intermediario entre los componentes del _gameplay_ y los controles de la interfaz de usuario.
El *Canvas* y el resto de _GameObjects_ de la interfaz de usuario pueden ser hijos de ese `UIController`, lo que facilita empaquetar cada uno con su vista en su propio _prefab_.

.Ejemplo de jerarquía de _GameObjects_ en una interfaz de usuario en Unity. 
include::diagrams/unity_ui_hierarchy.adoc[]

TIP: En Unity se suele recomendar que la interfaz de usuario se cargue en el juego desde su propia escena de forma aditiva, para poder trabajar en ella de forma independiente.

En Unreal Engine se pueden desarrollar interfaces de usuario usando Slate en {cpp} o visualmente con el editor UMG.
Una buena forma de combinar lo mejor de ambas opciones es crear un contenedor de controles personalizado heredando de `UUserWidget` en {cpp}.
Esa nueva clase hará de presentador, así que se implementa en ella la lógica relacionada con el acceso y transformación de los datos.
Después se hereda de ella en _blueprint_ para crear una nueva clase donde se pueden añadir fácilmente los controles desde el editor UMG y programar en _blueprint_ la lógica visual de la interfaz.

=== Data binding

El _data binding_ es un patrón de diseño de software que simplifica el diseño de interfaces gráficas.
Permite vincular elementos de la interfaz con una fuente datos, de tal forma que ambos se mantienen sincronizados automáticamente.

Por ejemplo, en un proyecto donde tengamos decenas o cientos de objetos o de personajes, con diferentes características que el usuario puede examinar en la interfaz e incluso modificar, es de gran utilidad tener un mecanismo que conecte de forma sencilla estos objetos con la interfaz, de manera que esta se actualice automáticamente.
En definitiva, algo así:

[source,csharp]
----
CharacterStatsPanel.Bind(CharacterStats);
----

Por lo general, los _frameworks_ de _data binding_ usan el patrón _observer_ como mecanismo subyacente.
La ventaja es que todo el proceso de suscripción y de actualización de los controles a partir de los datos, queda oculto detrás del `Bind()`.

[[fig-data-binding]]
.Diagrama de clases de un sencillo sistema de _data binding_.
include::diagrams/data_binding.adoc[]

En la <<fig-data-binding>> se puede ver lo que podría ser el diagrama de clases de un sistema de _data binding_.
Todo ocurre en `CharacterPanel::Bind()` que se encarga de suscribir el objeto `CharacterPanel` a los eventos del objeto `CharacterStat` indicado, de forma que cuando lleguen estos eventos, se ejecute código que actualice el panel.

Si se utiliza con el patrón de arquitectura MVP, el presentador puede ser el intermediario que localice a las entidades de los personajes y pida el _binding_, para mantener el desacople entre interfaz de usuario y lógica del juego.
Una vez hecho, la comunicación entre la vista y las características del personaje sería directa.

== Scriptable objects en Unity

Uno de los motivos para usar el patrón _singleton_ es porque facilita pasar datos de una escena a la siguiente.
Por eso en las dos implementaciones de _singleton_ que vimos en el <<_singleton>> se llama a `DontDestroyOnLoad()`, evitando la destrucción del objeto al cargar una nueva escena.

Como el abuso del patrón _singleton_ es un problema, muchos desarrolladores se han esforzado en buscar alternativas que faciliten organizar la arquitectura del programa, al tiempo que se limita en lo posible su uso.

Para resolver el problema de pasar información entre escenas, sin tener que lidiar con objetos que perviva entre ellas, haciendo que estas sean lo más independientes posibles; una de las alternativas que ha despertado más interés entre los desarrolladores de Unity son los _scriptable objects_.

=== Qué son

Los _scriptable objects_ son contenedores de datos que podemos personalizar como más nos convengan.
Son objetos de C# cuyos campos se almacenan como recursos en el editor, para después poder recuperar los objetos durante la ejecución.
Por lo tanto, sirven para cosas como: guardar configuración o crear una base de datos de habilidades o de objetos para el inventario.

Para que nos hagamos una idea de su flexibilidad, el sistema de animación de Unity se sustenta en los _scriptable objects_.

=== Cómo usarlos

Veamos un ejemplo extraído de <<Unity-Architect-With-SO>>, un artículo muy recomendable sobre cómo los _scriptable objects_ pueden ayudar a mejorar la arquitectura de nuestros juegos:

[source,csharp]
----
[CreateAssetMenu] <2>
public class FloatVariable : ScriptableObject
{
    public float Value; <1>
}
----
<1> Este _scriptable object_ solo tiene un campo público, pero podría tener más campos públicos, privados e incluso código, como cualquier clase de C#.
<2> Con el atributo `CreateAssetMenu` estamos añadiendo una opción al menú _asset_ que permita a cualquier miembro del equipo —incluso a los que no tiene conocimientos de programación— crear fácilmente recursos de tipo `FloatVariable`.

Ahora supongamos que vamos a usar uno de esos recursos para guardar el valor de salud del personaje.
Primero crearíamos el recurso, lo meteríamos en una carpeta, tal vez le daríamos el nombre `Health`, y luego le asignaríamos un valor.
Después, cualquier componente que quisiera usar el valor de `Health` necesitaría tener un campo de tipo `FloatVariable`, así:

[source,csharp]
----
[CreateAssetMenu]
public class MyComponent : ScriptableObject
{
    public FloatVariable health;

    // ...
}
----

Y así, desde el editor de Unity se podría asignar al campo _health_ del componente *MyComponent* el recurso `Health`, o cualquier otro _scriptable object_ de tipo `FloatVariable`.

Como los _scriptable objects_ pueden incluir código, es fácil añadir otras funcionalidades.
Por ejemplo, que `FloatVariable` emita un evento cuando `Value` cambie, permitiendo a todos los componentes de la escena interesados suscribirse para «escuchar» estos cambios.

=== Ventajas

Los _scriptable objects_ pueden hacernos la vida más fácil a la hora de organizar la arquitectura del juego.
Como hemos visto, se pueden usar para guardar variables —como la salud del jugador o el estado del juego— que van a ser utilizados en múltiples componentes de la escena.
Pero también sirven para implementar bases de datos, listas de elementos o crear _enums_ que los diseñadores puedan editar sin tener conocimientos de programación.

En <<Unity-Architect-With-SO>> también se sugiere usarlos para crear un bus de eventos del juego o incluso para implementar _managers_ y sistemas completos, evitando así el uso del patrón _singleton_.

Lo interesante es que de esta forma no hay que pelearse con tener objetos que pervivan a la carga de una escena.
Todas las escenas son independientes.
Cuando termina una se carga la siguiente, sin más.
Las escenas toman la información de los _scriptable objects_ y estos mantienen los valores modificados durante la ejecución, siempre que en las escenas haya al menos un componente con una referencia al _scriptable object_.

El «inconveniente» es que los componentes, en lugar de acceder a un _singleton_ directamente desde el código, deben tener una referencia pública a cada _manager_ al que necesitan acceder.
Por ejemplo, todos los componentes que necesiten acceder al `AudioManager` tendrán que tener un campo `AudioManager` accesible desde el editor, para desde él indicar el recurso _scritable object_ con el `AudioManager` que se quiere que use.

Aunque esto puede parecer tedioso, lo cierto es que el uso de _prefabs_ con valores preconfigurados por defecto, ayuda a que este trabajo no tenga que repetirse muchas veces.
Igualmente, se puede emplear el método `OnValidate()` de los componentes para asignar automáticamente valores por defecto a este tipo de campos.

Todo el interés sobre el uso de _scriptable objects_ para mejorar la arquitectura de los juegos surgió a raíz de una conferencia en Unite 2016:

[[video-unity-so-unite-2016, {video-caption} {counter:video-number}]]
.{video-caption} {video-number}. Conferencia «Overthrowing the MonoBehaviour Tyranny in a Glorious Scriptable Object Revolution» en Unite 2016.
video::6vmRwLYWNRo[youtube, opts="modest", start=808, end=1662, width=854, height=480]

A la que le siguió otra sobre el mismo tema el año siguiente, en Unite 2017.
Ambas son bastante ilustrativas y muestran varios ejemplos de cómo utilizar los _scriptable objects_.

[[video-unity-so-unite-2017, {video-caption} {counter:video-number}]]
.{video-caption} {video-number}. Conferencia «Game Architecture with Scriptable Objects» en Unite Austin 2017.
video::raQ3iHhE_Kk[youtube, opts="modest", start=808, end=1662, width=854, height=480]

[bibliography]
== Referencias

* [[[Martin2012,1]]] 
Martin, R.C. (2012). https://puntoq.ull.es/permalink/f/6auhvr/ullabsysULL00512351c-X[_Código limpio : manual de estilo para el desarrollo ágil de software_]. Anaya Multimedia. 

* [[[Martin2017,2]]] 
Martin, R.C. (2017). https://puntoq.ull.es/permalink/f/1rcchus/TN_safari_s1_9780134494272[_Clean Architecture: A Craftsman’s Guide to Software Structure and Design_]. Prentice Hall

* [[[Perez2020,3]]]
Perez, J. (2020, 9 de marzo). Libro resumido: Clean Code. _Juanma Perez Blog_.
https://juanmaperezblog.wordpress.com/2020/03/09/libro-resumido-clean-code/

* [[[Altadill,4]]]
Altadill, P. _Curso de Clean Code_. OpenWebinars. https://openwebinars.net/cursos/clean-code/

* [[[UE-Game-Framework,5]]]
Epic Games, Inc. Gameplay Framework. _Unreal Engine 4 Documentation_. 
https://docs.unrealengine.com/en-US/InteractiveExperiences/Framework/index.html

* [[[Wikipedia-Singleton,6]]]
Singleton. En _Wikipedia_. https://es.wikipedia.org/wiki/Singleton

* [[[Unity-RuntimeInitializeLoadType,7]]]
Unity Technologies. RuntimeInitializeLoadType. _Unity Manual_. https://docs.unity3d.com/ScriptReference/RuntimeInitializeLoadType.html

* [[[Unity-Domain-Reloading,8]]]
Unity Technologies. Domain Reloading. _Unity Manual_. https://docs.unity3d.com/Manual/DomainReloading.html

* [[[Wikipedia-State,9]]]
State (patrón de diseño). En _Wikipedia_. link:pass:[https://es.wikipedia.org/wiki/State_(patrón de diseño)][]

* [[[Wikipedia-FSM,10]]]
Autómata finito. En _Wikipedia_. https://es.wikipedia.org/wiki/Aut%C3%B3mata_finito

* [[[Wikipedia-Factory,11]]]
Factory Method (patrón de diseño). En _Wikipedia_. link:pass:[https://es.wikipedia.org/wiki/Factory_Method_(patrón de diseño)][]

* [[[Wikipedia-Abstract-Factory,12]]]
Abstract Factory. En _Wikipedia_. link:https://es.wikipedia.org/wiki/Abstract_Factory[]

* [[[Wikipedia-Strategy,13]]]
Strategy (patrón de diseño). En _Wikipedia_. link:pass:[https://es.wikipedia.org/wiki/Strategy_(patrón de diseño)][]

* [[[Wikipedia-Decorator,14]]]
Decorator (patrón de diseño). En _Wikipedia_. link:pass:[https://es.wikipedia.org/wiki/Decorator_(patrón de diseño)][]

* [[[Wikipedia-Visitor,15]]]
Visitor (patrón de diseño). En _Wikipedia_. link:pass:[https://es.wikipedia.org/wiki/Visitor_(patrón de diseño)][]

* [[[Wikipedia-Object-Pool,16]]]
Object pool (patrón de diseño). En _Wikipedia_. link:pass:[https://es.wikipedia.org/wiki/Object_pool_(patrón de diseño)][]

* [[[Contreras2019,17]]]
Conteras, V. (2019, 19 de septiembre). Patrón de diseño Object Pooling en Unity. _DEV_. https://dev.to/developervix/patron-de-diseno-object-pooling-en-unity-ecf

* [[[Wikipedia-Observer,18]]]
Observer (patrón de diseño). En _Wikipedia_. link:pass:[https://es.wikipedia.org/wiki/Observer_(patrón de diseño)][]

* [[[Microsoft-Delegates,19]]]
Microsoft Corporation. Utilizar delegados (Guía de programación de C#). _Guía de C#_.
https://docs.microsoft.com/es-es/dotnet/csharp/programming-guide/delegates/using-delegates

* [[[Microsoft-Events,20]]]
Microsoft Corporation. Procedimiento Suscribir y cancelar la suscripción a eventos (Guía de programación de C#). _Guía de C#_.
https://docs.microsoft.com/es-es/dotnet/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events

* [[[Dunstan2016,21]]]
Dunstan, J. (2016, 25 de enero). Event Performance: C# vs. UnityEvent. _JacksonDunstan.com_. https://www.jacksondunstan.com/articles/3335

* [[[UE-Delegates,22]]]
Epic Games, Inc. Delegates. _Unreal Engine 4 Documentation_. https://docs.unrealengine.com/en-US/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/Delegates/index.html

* [[[UE-Multicast-Delegates,23]]]
Epic Games, Inc. Multi-cast Delegates. _Unreal Engine 4 Documentation_. https://docs.unrealengine.com/en-US/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/Delegates/index.html

* [[[UE-Events,24]]]
Epic Games, Inc. Events. _Unreal Engine 4 Documentation_. https://docs.unrealengine.com/en-US/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/Delegates/Events/index.html

* [[[UE-Dynamic-Delegates,25]]]
Epic Games, Inc. Events. _Unreal Engine 4 Documentation_. https://docs.unrealengine.com/en-US/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/Delegates/Events/index.html

* [[[UE-Event-Dispatchers,26]]]
Epic Games, Inc. Dynamic Delegates. _Unreal Engine 4 Documentation_. https://docs.unrealengine.com/en-US/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/Delegates/Dynamic/index.html

* [[[Wikipedia-Corrutina,27]]]
Corrutina. En _Wikipedia_. https://es.wikipedia.org/wiki/Corrutina

* [[[Unity-Job-System,28]]]
Unity Technologies. Jobs System. _Unity Manual_. https://docs.unity3d.com/Manual/JobSystem.html

* [[[UE-FQueuedThreadPool,29]]]
Epic Games, Inc. FQueuedThreadPool. _Unreal Engine 4 Documentation_. 
https://docs.unrealengine.com/en-US/API/Runtime/Core/Misc/FQueuedThreadPool/index.html

* [[[Dunstan2015,30]]]
Dunstan, J. (2015, 2 de marzo). Unity Coroutine Performance. _JacksonDunstan.com_. https://www.jacksondunstan.com/articles/2981

* [[[Wikipedia-MVP,31]]]
MVP. En _Wikipedia_. https://es.wikipedia.org/wiki/Modelo%E2%80%93vista%E2%80%93presentador

* [[[Wikipedia-MVVM,32]]]
MVVM. En _Wikipedia_. https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel

* [[[Unity-Architect-With-SO,33]]]
Unity Technologies. (2020, enero). _Three ways to architect your game with ScriptableObjects_. Unity. https://unity.com/how-to/architect-game-code-scriptable-objects