= Desarrollo de Videojuegos 3D: Estructura del proyecto
Jesús Torres <jmtorres@ull.es>
include::../config/attributes.adoc[]
:imagesdir: {imagesdir}/estructura_del_proyecto
2019-2020

Poner algo de orden en un proyecto es importante para asegurar su mantenibilidad.
Facilita que cada miembro del equipo sepa donde buscar o añadir aquello que necesite para hacer su trabajo.
Por eso a continuación vamos a ver algunas buenas prácticas comunes.

== Organización de los recursos

Todos los motores tienen una carpeta donde incluir los recursos del proyecto.
Por ejemplo, en Unreal Engine es `Content` mientras que en Unity o CryEngine es `Assets`.
¿Pero como deberíamos organizar el contenido de dicha carpeta?.

Las opciones más comunes son:

* Por tipo de recurso.
* Por característica o funcionalidad en el juego:

=== Organización por tipo.

En tutoriales, cursos y proyectos pequeños es muy común que el primer nivel de carpetas se organicen los recursos por tipo de recursos.
Por ejemplo: `Scripts`, `Art`, `Audio`, `Blueprints` o `BP`, `Animations`, `Prefabs`, `Scenes`, `Levels`, `Sprites`, `Data`, etc.

[#img-assets-tree-by-type]
.Ejemplo de organización de los recursos del proyecto por tipo.
[plantuml, format="svg"]
....
salt
{
{T
 + Assets
 ++ <b>Art
 +++ Materials
 +++ Meshes
 +++ Textures
 ++ <b>Audio
 ++ <b>Prefabs
 ++ <b>Scenes
 ++ <b>Scripts
 ++ <b>Tests
}
}
....

Muchas veces, algunas de estas carpetas de primer nivel suelen tener un segundo nivel también organizado por tipo.
Por ejemplo, en la <<img-assets-tree-by-type>> la carpeta `Art` contiene: 'Meshes', 'Textures', 'Materials', etc.

Finalmente, suelen acabar creándose carpetas por característica o funcionalidad del juego en los niveles más profundos de la jerarquía.
Por ejemplo, dentro de `Meshes` o de `Scripts` los recursos del jugador se separan de los de los NPC usando carpetas diferentes.
Y dentro de los NPC, los recursos de personajes especiales, como el _Final Boss_ se separan del resto en carpetas propias.

[plantuml, format="svg"]
....
salt
{
{T
 + Assets
 ++ Art
 +++ Materials
 ++++ Player
 ++++ <b>NPC
 +++++ <b>Final Boss
 +++ Meshes
 ++++ Player
 ++++ <b>NPC
 +++++ <b>Final Boss
 +++ Textures
 ++++ Player
 ++++ <b>NPC
 +++++ <b>Final Boss
 ++ Audio
 +++ <b>NPC
 ++++ <b>Final Boss
 ++ Prefabs
 ++ Scenes
 ++ Scripts
 +++ Player
 +++ <b>NPC
 ++++ <b>Final Boss
 +++ UI
 ++ Tests
}
}
....

Si lo pensamos un momento, nos daremos cuenta que alguien que esté trabajando en el _Final Boss_ tiene que buscar y trabajar con recursos en ramas distintas del árbol de recursos.

=== Organización por característica

En proyectos más grandes, muchas veces se invierten las preferencias.
Es decir, el primer nivel se organizan por características, mientras que en niveles más profundos se organiza por tipos:

[plantuml, format="svg"]
....
salt
{
{T
 + Assets
 ++ <b>Environment
 +++ Level01
 ++++ Materials
 ++++ Meshes
 ++++ Textures
 ++ <b>NPC
 +++ <b>Final Boss
 ++++ Meshes
 ++++ Materials
 ++++ Scripts
 ++++ Sounds
 ++++ Textures
 +++ <b>Robots
 ++++ Meshes
 ++++ Materials
 ++++ Scripts
 ++++ Sounds
 ++++ Textures
 ++ <b>Player
 +++ Meshes
 +++ Materials
 +++ Scripts
 +++ Sounds
 +++ Textures
 ++ Prefabs
 ++ Scenes
 ++ Tests
 ++ <b>UI
}
}
....

En este caso es muy probable que alguien que esté trabando en una característica concreta tenga todo lo que necesita en un única rama de la jerarquía de recursos.

=== Unity

Debido a las particularidades de Unity, se deben considerar algunos consejos adicionales.

==== No importar más de lo necesario

Durante mucho tiempo una de las principales características de Unity fue su _Asset Store_.
Sin duda hace muy sencillo encontrar y utilizar recursos, tanto para prototipar como para el desarrollo del producto final.
Sin embargo, también hace que sea muy sencillo cargar nuestro proyecto con recursos, ejemplos y documentación que no necesitamos.

Por eso es importante seleccionar solo lo que realmente nos interesa durante el proceso de importación.
Por si no estamos seguros, es buena idea tener un proyecto vació donde importar los paquetes desde la _Asset Store_ para luego exportar solo los _prefabs_ que nos interesen con sus dependencias.
Incluso podemos modificarlos en este proyecto antes de exportarlos, si fuera necesario eliminar algún componente que no nos interese.

El paquete exportado es el que importaríamos en nuestro proyecto, para así asegurarnos que sólo metemos lo que realmente vamos a utilizar.

==== Contenidos propios en la carpeta "GameAssets"

[#img-unit-gameassets]
.Ejemplo de organización de los recursos usando la carpeta 'GameAssets'.
[plantuml, format="svg"]
....
salt
{
{T
 + Assets
 ++ <b>GameAssets
 +++ <b>_Scripts
 +++ Art
 ++++ Materials
 ++++ Meshes
 ++++ Textures
 +++ Audio
 +++ <b>Scenes
 +++ Prefabs
 +++ Tests
 ++ ProCore
 ++ Standard Assets
}
}
....

Algunos desarrolladores prefieren colocar la jerarquía de recursos propios del proyecto dentro su propia carpeta.
Por ejemplo, en la <<img-unit-gameassets>> se observa como la jerarquía de la <<img-assets-tree-by-type>> ahora está dentro de una carpeta llamada path[GameAssets] en el primer nivel de `Assets`.

El motivo es que en Unity los _plugins_ y _assets_ importados desde el _Asset Store_ se copian directamente en `Assets`, mezclándose con las carpetas con contenidos propios.
Eso complica mantener una estructura organizada donde se separe qué es nuestro y qué un plugin o recurso importado.

[TIP]
====
En la <<img-unit-gameassets>> también se puede ver otra práctica que puede resultar interesante a los desarrolladores.
Se trata de llamar `_Scripts` a la carpeta que contiene el código en C#.
El motivo es que así aparece la primera del proyecto y, por tanto, es más fácil de localizar.
====

==== Evitar el uso de "Resources"

`Resources` es una carpeta especial en `Assets` donde colocar recursos que van a ser cargados dinámicamente, durante la ejecución.

Debido a que esos recursos van a ser cargados dinámicamente, Unity no puede detectar los recursos en `Resources` que nunca son usados en el proyecto, para dejarlos fuera de la compilación.
Así que los incluirá todos.

TIP: Actualmente para utilizar contenidos dinámicos es mucho mejor utilizar https://docs.unity3d.com/Packages/com.unity.addressables@0.4/manual/index.html[Addresables].

==== Usar Assembly Definitions

Por defecto Unity compila todos el código C# en `Assembly-CSharp.dll`.
Esto significa que cada vez que se modificar alguna parte del código se tiene que compilar todo, lo que puede consumir bastante tiempo en proyectos grandes.

Los https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html[Assembly Definitions] permiten que una carpeta y sus subcarpetas se compile en una DLL diferente.
Esto reduce los tiempos de compilación porque si se modifica un archivo de código, sólo se compilan los archivos incluidos en la misma DLL.

Además los _Assembly Definitions_ son necesarios para hacer tests del código del proyecto.

== Jerarquía de la escena

También es conveniente fijar ciertas reglas sobre la organización de la jerarquía de objetos en la escena.

En general es buena idea agrupa los elementos de la escena atendiendo a su papel en el juego o a su tipo.

[plantuml, format="svg"]
....
salt
{
{T
+ Scene
 ++ Main Camera
 ++ <b>Environment
 +++ <b>Buildings
 +++ <b>Lights
 +++ <b>Vehicles
 +++ <b>Roads
 +++ <b>Props
 ++ <b>Enemies
 ++ Player
}
}
....

Para eso Unreal ofrece carpetas en su _World Outliner_ mientras que Unity obliga a introducir _GameObjects_ vacíos.

=== Unity

El matiz anterior es importante, porque las carpetas de Unreal Engine solo son una ayuda del editor.
No existen para el motor.
Pero los _GameObjects_ de Unity, incluso cuando están vacíos, si pueden afectar al rendimiento si no se usan adecuadamente.

Básicamente Unity hace lo siguiente:

* Cada _GameObject_ en el primer nivel de la escena conforma un árbol de objetos.

* Si cualquier _GameObject_ de un árbol se mueve, Unity examinará los componentes _Transform_ de todos los objetos del mismo árbol para notificar los cambios a los componentes del motor que lo pidan.

* Unity utiliza un _pool_ de hilos internos para examinar los árboles de forma independiente en hilos separados.

Así que la regla general es que es mejor tener muchos árboles en la raíz de la escena con pocos objetos, que un único gran árbol con todos los objetos.

A efectos prácticos esto se traduce en que:

* Como los objetos estáticos del escenario —mallas, luces, terreno, etc— no se mueven, por lo que se pueden poner todos juntos en un único árbol, lo que resulta muy cómodo para organizar esos objetos en la escena.

* Por el mismo motivo, los _GameObject_ de _gameplay_ —el jugador, los enemigos, etc.— deberían estar en la raíz. Y los _GameObject_ creados dinámicamente nunca hacerlos hijos de quién los creó a menos que tengan que moverse con ese objeto.

[TIP]
====
Si para facilitar el trabajo se prefiere agrupar estos objetos de _gameplay_ como hijos de algún _GameObject_, se puede crear un _plugin_ del editor que los mueva a la raíz antes de compilar o de entrar en el modo de ejecutar el juego.
====

Una recomendación que simplifica la colaboración entre desarrolladores y que ayudar a mantener la jerarquía de objetos organizada, aunque haya que tener muchos en la raíz de la escena, es componer el nivel con la unión de varias escenas aditivas:

[plantuml, format="svg"]
....
salt
{
{T
 + <b>Level01
 ++ Main Camera
 ++ Environment
 +++ Buildings
 +++ Lights
 +++ Vehicles
 +++ Roads
 +++ Props
 ++ Player
 + <b>Mission01
 ++ Environment
 +++ Vehicles
 +++ Props
 ++ Enemy01
 ++ Enemy02
 ++ Enemy03
 ++ ...
 + <b>UI
 ++ HUD
}
}
....
