flowchart BT

subgraph Engine["Motor de videojuegos"]
    direction LR
    GameEngine --> IEngine["<i>«Interface»</i><br>IEngine"]
end

subgraph GameTools["Herramientas"]
    direction TB
    Map["Editor de niveles"] ~~~ Personajes ~~~ Animación ~~~ SettingsEditor["Configuración"]
end

subgraph GameContent["Contenidos"]
    direction TB
    Texturas ~~~ Modelos ~~~ Sonidos ~~~ UI ~~~ Settings["Configuración"]
end

subgraph GameUtility["Utilidades"]
    direction TB
    DataPersistence["Persistencia de datos"] ~~~ Analytics["Sistema de analíticas"] ~~~ MathLib["Librería matemática"]
end

GameTools --- Engine 
GameContent --- Engine 
GameUtility --- Engine