name: Publicar

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Obtener el proyecto
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Generar la documentación
      uses: devcontainers/ci@v0.2
      with:
        runCmd: quarto render --to pdf

    - name: Empaquetar la documentación
      run: find _output/ -type f -iname '*.pdf' | zip -j  _output/desarrollo3d.zip -@

    - name: Publicar en 'Releases'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: _output/{**/*.pdf,desarrollo3d.zip}
        file_glob: true
        body: "Apuntes de Desarrollo de Videojuegos 3D del curso 20XX-20XY."
        release_name: "Curso 20XX-20XY"
        prerelease: true
        overwrite: true