name: Publish Website

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - id: dotenv
      name: Read environment variables
      uses: falti/dotenv-action@v1.1.4
      with:
        path: ./_environment-prod
        log-variables: true

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Publish to GitHub Pages
      uses: quarto-dev/quarto-actions/publish@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        QUARTO_PROFILE: prod
      with:
        target: gh-pages

    - name: Package documentation
      run: cd _book && zip -r ../desarrollo3d.zip *

    - name: Publish the documentation to 'Releases'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: desarrollo3d.zip
        body: "Apuntes de Desarrollo de Videojuegos 3D del curso ${{ steps.dotenv.outputs.academic_year }}."
        release_name: "Curso ${{ steps.dotenv.outputs.academic_year }}"
        prerelease: true
        overwrite: true
